import { createRecoraTopicSourceRowsV3 } from "./measurement-topic-contract";
import type { RecoraTopicBlueprintSourceRowV3 } from "./measurement-topic-contract";

export const RECORA_TOPIC_STRUCTURE_SOURCE_ROWS_V3 = [
  ...createRecoraTopicSourceRowsV3("b2b_buying", [
    ["b2b.business_case_roi","導入効果・費用対効果・事業上の必要性","pricing_and_value","T3","criteria_explanation"],
    ["b2b.internal_approval_readiness","稟議・経営承認に必要な説明材料","action_readiness","T4","action_readiness"],
    ["b2b.budget_ownership","予算枠・費用負担部門・投資時期への適合","pricing_and_value","T3","criteria_explanation",["service","comparison_criterion","price_fee"]],
    ["b2b.procurement_requirements","見積・取引条件・購買手続き・選定要件","action_readiness","T4","action_readiness",["service","action_requirement","contract_condition"]],
    ["b2b.contract_governance","契約期間・責任・更新・解約・管理条件","action_readiness","T4","action_readiness",["service","action_requirement","contract_condition"]],
    ["b2b.implementation_readiness","導入手順・移行・教育・立上げ条件","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["b2b.adoption_change_management","社内浸透・利用定着・運用変更の負荷","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["b2b.vendor_support_model","導入後支援・問い合わせ・SLA・担当体制","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["b2b.vendor_risk_continuity","ベンダー継続性・障害・撤退・依存リスク","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["b2b.governance_compliance_fit","社内規程・監査・統制・法令への適合","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("b2c_decision", [
    ["b2c.personal_goal_fit","本人の目的・悩み・利用場面への適合","fit_and_selection","T3","criteria_explanation"],
    ["b2c.affordability_total_cost","本体価格・追加費用・継続費用を含む負担可能性","pricing_and_value","T3","criteria_explanation",["service","comparison_criterion","price_fee"]],
    ["b2c.social_proof_reviews","口コミ・体験談を過信せず参考にする条件","trust_and_reputation","T5","trust_risk_diagnostic",["service","evidence_source","review_reputation_signal"]],
    ["b2c.safety_caution_fit","安全性・注意点・向かない条件","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["b2c.convenience_accessibility","時間・場所・操作・利用しやすさ","fit_and_selection","T3","criteria_explanation"],
    ["b2c.first_time_confidence","初回利用前の不安・準備・失敗条件","action_readiness","T4","action_readiness"],
    ["b2c.payer_recipient_difference","支払者と利用者が異なる場合の条件","fit_and_selection","T4","criteria_explanation"],
    ["b2c.post_purchase_support_returns","購入・申込後の支援・返品・変更・問い合わせ","action_readiness","T4","action_readiness"],
  ]),
  ...createRecoraTopicSourceRowsV3("both_audience", [
    ["both.offer_scope_difference","法人向けと個人向けの提供範囲の違い","fit_and_selection","T3","criteria_explanation"],
    ["both.audience_priority_alignment","優先顧客層に適した利用条件","fit_and_selection","T3","criteria_explanation"],
    ["both.pricing_contract_difference","法人契約と個人購入・申込の料金・契約差","action_readiness","T4","action_readiness",["service","action_requirement","contract_condition"]],
    ["both.support_delivery_difference","法人・個人の支援体制・提供方法・責任範囲の違い","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["both.access_usage_condition_difference","アカウント・権限・利用者数・利用条件の違い","action_readiness","T4","action_readiness"],
  ]),
  ...createRecoraTopicSourceRowsV3("family_proxy", [
    ["family.guardian_decision_conditions","保護者が選択・申込・契約する際の条件","action_readiness","T4","action_readiness"],
    ["family.need_interpretation","本人の状態・希望を家族が整理して候補へ結び付ける条件","fit_and_selection","T1","criteria_explanation"],
    ["family.alternate_payer_conditions","利用者と異なる支払者の費用・契約条件","action_readiness","T4","action_readiness"],
    ["family.co_decision_alignment","家族・同居人との共同判断条件","fit_and_selection","T3","criteria_explanation"],
    ["family.dependent_recipient_fit","子ども・高齢者・支援対象者本人への適合","fit_and_selection","T3","criteria_explanation"],
    ["family.formal_proxy_consent","代理権・同意・手続き・必要書類","trust_and_reputation","T5","trust_risk_diagnostic"],
  ]),
  ...createRecoraTopicSourceRowsV3("agency_delivery", [
    ["agency.client_use_case_fit","最終顧客の案件・課題への適用","fit_and_selection","T3","criteria_explanation"],
    ["agency.multi_client_operations","複数顧客・複数案件の運用","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["agency.white_label_branding","ホワイトラベル・再販・顧客名義提供の条件","action_readiness","T4","action_readiness"],
    ["agency.evidence_reporting","顧客へ説明できる根拠・レポート・監査可能性","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["agency.delivery_handoff","提案・設定・運用・顧客引継ぎの責任分界","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["agency.margin_resale_pricing","仕入・手数料・利益・再販価格の成立性","fit_and_selection","T3","criteria_explanation"],
    ["agency.responsibility_boundary","提供会社・代理店・最終顧客の責任範囲","trust_and_reputation","T5","trust_risk_diagnostic"],
  ]),
  ...createRecoraTopicSourceRowsV3("b2b2c", [
    ["b2b2c.sponsor_business_case","導入組織側の費用・契約・成果責任","fit_and_selection","T3","criteria_explanation"],
    ["b2b2c.client_operator_workflow","組織側運用担当の設定・案内・利用者対応","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["b2b2c.beneficiary_experience_fit","最終利用者・受益者の利用しやすさ","fit_and_selection","T3","criteria_explanation"],
    ["b2b2c.adoption_communication","利用開始案内・教育・参加促進・問い合わせ導線","action_readiness","T4","action_readiness"],
    ["b2b2c.outcome_accountability","組織側の成果・品質の説明・評価","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["b2b2c.data_privacy_responsibility","導入組織・提供会社・利用者間のデータ責任","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("marketplace_demand", [
    ["marketplace.demand_listing_discovery","需要側の商品・サービス・提供者の掲載候補発見","candidate_discovery","T1","market_discovery",["marketplace_listing","market_side_participant","solution_category"]],
    ["marketplace.demand_listing_comparison","需要側の出品・提供者・条件比較","comparison","T2","market_comparison",["marketplace_listing","market_side_participant","comparison_criterion"]],
    ["marketplace.demand_transaction_trust","本人確認・評価・不正・取引安全性","trust_and_reputation","T5","trust_risk_diagnostic",["marketplace_listing","market_side_participant","evidence_source"]],
    ["marketplace.demand_total_price_fees","本体価格・手数料・追加費用・支払条件","action_readiness","T4","action_readiness",["marketplace_listing","market_side_participant","action_requirement","price_fee"]],
    ["marketplace.demand_fulfillment_quality","配送・予約・納品・サービス実行品質","fit_and_selection","T3","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion"]],
    ["marketplace.demand_dispute_refund","キャンセル・紛争・返金・補償条件","action_readiness","T4","action_readiness",["marketplace_listing","market_side_participant","action_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("marketplace_supply", [
    ["marketplace.supply_participation_fit","供給者・出品者として参加する価値と適合","fit_and_selection","T3","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion"]],
    ["marketplace.supply_onboarding_requirements","審査・登録・必要情報・参加開始条件","action_readiness","T4","action_readiness",["marketplace_listing","market_side_participant","action_requirement"]],
    ["marketplace.supply_commission_payout","手数料・入金・精算・売上条件","action_readiness","T4","action_readiness",["marketplace_listing","market_side_participant","action_requirement","price_fee"]],
    ["marketplace.supply_listing_inventory_operations","掲載・在庫・予約枠・価格・情報更新運用","implementation_and_operation","T6","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion","operational_requirement"]],
    ["marketplace.supply_demand_quality","顧客・案件・取引機会の質と量","trust_and_reputation","T3","trust_risk_diagnostic",["marketplace_listing","market_side_participant","evidence_source"]],
    ["marketplace.supply_rules_compliance","規約・品質基準・ペナルティ・禁止事項","regulated_risk","T5","trust_risk_diagnostic",["marketplace_listing","market_side_participant","evidence_source","risk_caution"]],
    ["marketplace.supply_retention_switching","継続出品・他Marketplace併用・退出条件","continuation_and_switching","T3","market_comparison",["marketplace_listing","market_side_participant","comparison_criterion"]],
  ]),
  ...createRecoraTopicSourceRowsV3("marketplace_operator", [
    ["marketplace.operator_liquidity_balance","需要・供給の量・質・地域・カテゴリのバランス","implementation_and_operation","T6","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion","operational_requirement"]],
    ["marketplace.operator_trust_safety","不正・審査・安全・本人確認・品質監視","regulated_risk","T5","trust_risk_diagnostic",["marketplace_listing","market_side_participant","evidence_source","risk_caution"]],
    ["marketplace.operator_quality_governance","掲載品質・提供品質・評価制度・基準運用","trust_and_reputation","T5","trust_risk_diagnostic",["marketplace_listing","market_side_participant","evidence_source"]],
    ["marketplace.operator_dispute_operations","問い合わせ・紛争・返金・エスカレーション運用","implementation_and_operation","T6","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion","operational_requirement"]],
    ["marketplace.operator_monetization_model","手数料・広告・会員・収益化と参加者負担","fit_and_selection","T3","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion"]],
    ["marketplace.operator_platform_operations","掲載・取引・決済・通知・サポート運用","implementation_and_operation","T6","criteria_explanation",["marketplace_listing","market_side_participant","comparison_criterion","operational_requirement"]],
    ["marketplace.operator_regulatory_data_governance","法令・データ管理・監査・説明責任","trust_and_reputation","T5","trust_risk_diagnostic",["marketplace_listing","market_side_participant","evidence_source"]],
  ]),
  ...createRecoraTopicSourceRowsV3("multi_location", [
    ["multilocation.location_discovery","条件に合う拠点・店舗・施設の発見","candidate_discovery","T1","market_discovery",["location_facility","solution_category"]],
    ["multilocation.location_difference","拠点ごとのサービス・設備・料金・営業時間の比較","comparison","T2","market_comparison",["location_facility","comparison_criterion"]],
    ["multilocation.brand_consistency","全拠点の品質・ルール・ブランド一貫性","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source"]],
    ["multilocation.availability_inventory","空き・在庫・予約枠・提供可能状況","action_readiness","T4","action_readiness",["location_facility","action_requirement"]],
    ["multilocation.local_reputation","拠点別口コミ・評判・地域適合","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source","review_reputation_signal"]],
    ["multilocation.cross_location_booking_use","別拠点利用・変更・振替・共通会員条件","action_readiness","T6","action_readiness",["location_facility","action_requirement","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("franchise", [
    ["franchise.investment_fit","加盟事業としての適合","fit_and_selection","T3","criteria_explanation"],
    ["franchise.territory_market","商圏・地域条件・競合・出店余地","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["franchise.unit_economics","初期費用・ロイヤリティ・収益構造・回収条件","pricing_and_value","T3","criteria_explanation",["service","comparison_criterion","price_fee"]],
    ["franchise.hq_support","研修・集客・仕入・運営・本部支援","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["franchise.operating_standards","ブランド基準・品質・業務手順・現場運営","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["franchise.brand_compliance_local_experience","本部基準と地域顧客体験の両立","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("subscription_membership", [
    ["subscription.acquisition_trial","新規加入前の体験・無料期間・開始条件","continuation_and_switching","T4","action_readiness",["service","action_requirement","contract_condition"]],
    ["subscription.ongoing_value","継続利用で得られる価値・頻度・内容","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","contract_condition","operational_requirement"],{"applicability":{"lifecycleSignalsAny":["active_user","renewal_decider","cancellation_decider","switching_evaluator"]}}],
    ["subscription.renewal_conditions","自動更新・更新時期・価格変更・継続条件","continuation_and_switching","T4","action_readiness",["service","action_requirement","contract_condition"],{"applicability":{"lifecycleSignalsAny":["active_user","renewal_decider","cancellation_decider","switching_evaluator"]}}],
    ["subscription.pause_cancellation","休止・解約・再開・返金条件","continuation_and_switching","T4","action_readiness",["service","action_requirement","contract_condition"],{"applicability":{"lifecycleSignalsAny":["active_user","renewal_decider","cancellation_decider","switching_evaluator"]}}],
    ["subscription.plan_change_upgrade","プラン変更・追加・縮小・アップグレード条件","continuation_and_switching","T3","action_readiness",["service","action_requirement","contract_condition"],{"applicability":{"lifecycleSignalsAny":["active_user","renewal_decider","cancellation_decider","switching_evaluator"]}}],
  ]),
  ...createRecoraTopicSourceRowsV3("urgent_service", [
    ["urgent.response_time_availability","即時対応可能な候補・対応時間・連絡方法","candidate_discovery","T1","market_discovery"],
    ["urgent.emergency_price_transparency","緊急料金・出張費・追加費用・見積条件","trust_and_reputation","T4","trust_risk_diagnostic",["service","evidence_source","price_fee"]],
    ["urgent.qualification_safety","資格・本人確認・安全手順・保険","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","qualification_registration","risk_caution"]],
    ["urgent.service_area_access","対応地域・到着目安・訪問条件","action_readiness","T6","action_readiness",["service","action_requirement","operational_requirement"]],
    ["urgent.post_service_warranty","作業後保証・再対応・トラブル時連絡先","trust_and_reputation","T5","trust_risk_diagnostic"],
  ]),
  ...createRecoraTopicSourceRowsV3("public_nonprofit", [
    ["public.program_service_eligibility","制度・支援・公共サービスの対象条件","fit_and_selection","T3","criteria_explanation"],
    ["public.procurement_requirements","入札・調達・契約・必要書類・評価要件","action_readiness","T4","action_readiness",["service","action_requirement","contract_condition"]],
    ["public.accessibility_inclusion","アクセシビリティ・多言語・配慮・利用しやすさ","trust_and_reputation","T6","trust_risk_diagnostic",["service","evidence_source","operational_requirement"]],
    ["public.accountability_disclosure","公開情報・説明責任・評価・監査可能性","regulated_risk","T5","trust_risk_diagnostic"],
    ["nonprofit.funding_donor_value","助成・寄付・協賛の目的・成果・資金利用","trust_and_reputation","T3","trust_risk_diagnostic"],
    ["public.beneficiary_outcome_evidence","住民・利用者・受益者への成果根拠","trust_and_reputation","T5","trust_risk_diagnostic"],
  ]),
  ...createRecoraTopicSourceRowsV3("manufacturer_channel", [
    ["channel.technical_spec_fit","製品仕様・用途・互換性・性能条件","implementation_and_operation","T6","criteria_explanation",["company","comparison_criterion","operational_requirement"]],
    ["channel.distributor_procurement","卸・流通側の仕入条件・価格・納期","action_readiness","T4","action_readiness",["company","action_requirement","contract_condition"]],
    ["channel.dealer_availability","販売店・在庫・地域・納品可能性","candidate_discovery","T1","market_discovery",["company","solution_category"]],
    ["channel.partner_support","販売支援・教育・営業資料・問い合わせ体制","trust_and_reputation","T5","trust_risk_diagnostic",["company","evidence_source"]],
    ["channel.maintenance_lifecycle","保守・部品・交換・更新・廃止条件","implementation_and_operation","T6","criteria_explanation",["company","comparison_criterion","operational_requirement"]],
    ["channel.total_cost_compliance","総保有コスト・安全基準・規格・法令適合","regulated_risk","T5","trust_risk_diagnostic",["company","evidence_source","price_fee","risk_caution"]],
  ]),
] as const satisfies readonly RecoraTopicBlueprintSourceRowV3[];
