import { createRecoraTopicSourceRowsV3 } from "./measurement-topic-contract";
import type { RecoraTopicBlueprintSourceRowV3 } from "./measurement-topic-contract";

export const RECORA_TOPIC_INDUSTRY_SOURCE_ROWS_V3 = [
  ...createRecoraTopicSourceRowsV3("company_brand", [
    ["company.company_candidate_discovery","課題に対応できる企業・事業者候補の発見","candidate_discovery","T1","market_discovery",["company","solution_category"]],
    ["brand.brand_differentiation","ブランド間の特徴・対象・提供価値の違い","comparison","T2","market_comparison",["company","comparison_criterion"]],
    ["company.corporate_trust_reputation","運営主体・企業実績・透明性・評判","trust_and_reputation","T5","trust_risk_diagnostic",["company","evidence_source","review_reputation_signal"]],
    ["brand.portfolio_relationship","会社・親ブランド・サービス・商品・拠点の関係","trust_and_reputation","T3","trust_risk_diagnostic",["company","evidence_source"]],
  ]),
  ...createRecoraTopicSourceRowsV3("offering_service", [
    ["service.scope_fit","対応できる課題・作業・対象・除外範囲","fit_and_selection","T3","criteria_explanation"],
    ["service.delivery_model","オンライン・対面・訪問・代行・共同運用等の提供方法","fit_and_selection","T3","criteria_explanation"],
    ["service.process_workflow","相談・開始・実施・報告・完了までの流れ","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["service.provider_responsibility","提供会社と顧客の作業・責任分界","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["service.outcome_expectation","提供可能な成果と保証できない範囲","trust_and_reputation","T3","trust_risk_diagnostic"],
    ["service.support_communication","連絡方法・担当体制・対応時間・エスカレーション","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["service.customization_options","個別要件・追加対応・プラン調整","fit_and_selection","T3","criteria_explanation"],
    ["service.availability_capacity","対応可能時期・枠・納期・受入能力","action_readiness","T4","action_readiness"],
    ["managed_service.operating_model","継続代行の運用範囲・頻度・定例・役割","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"],{"applicability":{"primaryOfferingModelsAny":["managed_service"]}}],
    ["managed_service.reporting_visibility","報告内容・進捗・成果指標・作業可視性","trust_and_reputation","T5","trust_risk_diagnostic",null,{"applicability":{"primaryOfferingModelsAny":["managed_service"]}}],
    ["advisory.consultation_process","初回相談・ヒアリング・提案・助言の流れ","action_readiness","T4","action_readiness",null,{"applicability":{"primaryOfferingModelsAny":["professional_advisory"]}}],
    ["advisory.scope_limitation","助言範囲・専門外・最終判断責任","trust_and_reputation","T5","trust_risk_diagnostic",null,{"applicability":{"primaryOfferingModelsAny":["professional_advisory"]}}],
    ["consumer_service.experience_fit","利用体験・時間・負担・本人への適合","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"],{"applicability":{"primaryOfferingModelsAny":["consumer_service"]}}],
    ["consumer_service.aftercare_followup","利用後対応・再相談・保証・継続支援","trust_and_reputation","T5","trust_risk_diagnostic",null,{"applicability":{"primaryOfferingModelsAny":["consumer_service"]}}],
  ]),
  ...createRecoraTopicSourceRowsV3("offering_product", [
    ["product.use_case_fit","用途・目的・利用環境への製品適合","fit_and_selection","T3","criteria_explanation",["product","comparison_criterion"]],
    ["product.spec_quality","仕様・素材・性能・品質の違い","implementation_and_operation","T6","criteria_explanation",["product","comparison_criterion","operational_requirement"]],
    ["product.compatibility_fit","周辺機器・環境・サイズ・規格との互換性","fit_and_selection","T3","criteria_explanation",["product","comparison_criterion"]],
    ["product.warranty_lifecycle","保証・修理・交換・耐用期間・部品供給","trust_and_reputation","T5","trust_risk_diagnostic",["product","evidence_source"]],
    ["product.purchase_channel","正規店・EC・販売店・在庫・納期・購入条件","action_readiness","T4","action_readiness",["product","action_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("location_facility", [
    ["location.nearby_facility_discovery","条件に合う近隣店舗・施設・拠点の発見","candidate_discovery","T1","market_discovery",["location_facility","solution_category"]],
    ["location.access_transport_parking","住所・交通・駐車・徒歩・バリアフリー","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"]],
    ["location.hours_availability","営業時間・休業日・受付時間・空き状況","action_readiness","T4","action_readiness",["location_facility","action_requirement"]],
    ["location.booking_walkin_conditions","予約方法・当日受付・キャンセル・待ち時間","action_readiness","T4","action_readiness",["location_facility","action_requirement"]],
    ["location.facility_equipment_environment","設備・個室・衛生・環境・利用条件","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"]],
    ["location.staff_service_experience","スタッフ対応・サービス品質・利用者体験","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source"]],
    ["location.first_visit_preparation","初回来店時の持ち物・手続き・流れ・不安点","action_readiness","T4","action_readiness",["location_facility","action_requirement"]],
    ["location.alternate_location_transfer","別拠点・振替・転院・転校・店舗変更条件","comparison","T3","market_comparison",["location_facility","comparison_criterion"]],
  ]),
  ...createRecoraTopicSourceRowsV3("professional_person", [
    ["professional.expertise_scope","専門分野・対応領域・得意・対象外","fit_and_selection","T3","criteria_explanation",["professional_person","comparison_criterion"]],
    ["professional.credentials_registration","資格・免許・登録・所属・認証","trust_and_reputation","T5","trust_risk_diagnostic",["professional_person","evidence_source","qualification_registration"]],
    ["professional.track_record_case_fit","経験・事例・担当実績・相談内容への適合","trust_and_reputation","T5","trust_risk_diagnostic",["professional_person","evidence_source"]],
    ["professional.communication_fit","説明方法・相談しやすさ・対応方針との相性","fit_and_selection","T3","criteria_explanation",["professional_person","comparison_criterion"]],
    ["professional.availability_referral","予約可能性・担当指名・紹介・他専門家連携","action_readiness","T4","action_readiness",["professional_person","action_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("saas_software", [
    ["saas.feature_workflow_fit","機能と対象業務・ワークフローの適合","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["saas.integration_api","API・外部サービス・既存システム連携","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["saas.data_import_migration","データ取込・移行・出力・移行期間","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["saas.permissions_administration","権限・ユーザー管理・組織・監査ログ","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["saas.onboarding_implementation","初期設定・導入支援・教育・立上げ期間","action_readiness","T4","action_readiness"],
    ["saas.reliability_performance","稼働率・速度・障害・バックアップ","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["saas.support_sla","サポート窓口・対応時間・SLA・障害連絡","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["saas.scalability_pricing","利用者数・データ量・機能拡張と価格増加","fit_and_selection","T3","criteria_explanation"],
  ]),
  ...createRecoraTopicSourceRowsV3("enterprise_it_security", [
    ["enterprise.security_architecture","暗号化・ネットワーク・構成・セキュリティ設計","regulated_risk","T6","trust_risk_diagnostic",["service","evidence_source","risk_caution","operational_requirement"]],
    ["enterprise.identity_access_management","SSO・MFA・権限・アカウント管理","trust_and_reputation","T6","trust_risk_diagnostic",["service","evidence_source","operational_requirement"]],
    ["enterprise.privacy_data_protection","個人情報・保存場所・利用目的・データ保護","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["enterprise.compliance_audit","認証・監査・規制・証跡・社内基準","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["enterprise.vendor_risk_bcp","事業継続・障害・復旧・委託先・撤退リスク","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["enterprise.deployment_standardization","全社標準・複数環境・展開方法・変更管理","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["enterprise.security_incident_response","インシデント通知・対応・責任・再発防止","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("commerce_product", [
    ["commerce.product_need_fit","利用目的・悩み・使用場面に合う商品","fit_and_selection","T3","criteria_explanation",["product","comparison_criterion"]],
    ["commerce.materials_ingredients_specs","素材・成分・サイズ・仕様・使用条件","implementation_and_operation","T6","criteria_explanation",["product","comparison_criterion","operational_requirement"]],
    ["commerce.price_bundle_discount","単価・セット・割引・送料・総額","pricing_and_value","T3","criteria_explanation",["product","comparison_criterion","price_fee"]],
    ["commerce.delivery_fulfillment","配送地域・納期・送料・受取・在庫","action_readiness","T4","action_readiness",["product","action_requirement"]],
    ["commerce.returns_exchange","返品・交換・返金・初期不良・条件","action_readiness","T4","action_readiness",["product","action_requirement"]],
    ["commerce.subscription_repeat_purchase","定期購入・再購入・休止・解約・頻度","continuation_and_switching","T3","action_readiness",["product","action_requirement","contract_condition"],{"applicability":{"structureSignalsAll":["commerce_subscription"]}}],
    ["commerce.authorized_purchase_channel","公式・正規販売店・Marketplace・保証対象","trust_and_reputation","T5","trust_risk_diagnostic",["product","evidence_source"]],
    ["commerce.gift_recipient_occasion_fit","贈る相手・用途・時期・包装・受取条件への適合","implementation_and_operation","T6","criteria_explanation",["product","comparison_criterion","operational_requirement"],{"applicability":{"structureSignalsAll":["commerce_gift"]}}],
  ]),
  ...createRecoraTopicSourceRowsV3("healthcare_clinic", [
    ["healthcare.care_need_scope","相談内容と診療・施術・支援範囲の適合","fit_and_selection","T3","criteria_explanation",["professional_person","comparison_criterion"]],
    ["healthcare.provider_qualification_specialty","医師・専門職の資格・専門領域・対応経験","regulated_risk","T6","trust_risk_diagnostic",["professional_person","evidence_source","qualification_registration","operational_requirement"]],
    ["healthcare.consultation_booking_flow","初回相談・予約・受付・紹介状・当日の流れ","action_readiness","T4","action_readiness",["professional_person","action_requirement"]],
    ["healthcare.fees_insurance_payment","料金・保険適用・自由診療・追加費用・支払方法","action_readiness","T4","action_readiness",["professional_person","action_requirement","price_fee"]],
    ["healthcare.treatment_risk_explanation","リスク・限界・代替・説明・同意の確認点","regulated_risk","T5","trust_risk_diagnostic",["professional_person","evidence_source","risk_caution"]],
    ["healthcare.official_medical_information","公式情報・学会・行政等の根拠・更新状況","trust_and_reputation","T5","trust_risk_diagnostic",["professional_person","evidence_source"]],
    ["healthcare.continuation_referral_alternative","継続・他院・紹介・セカンドオピニオン等の選択肢","alternative_search","T2","market_comparison",["professional_person","comparison_criterion"]],
  ]),
  ...createRecoraTopicSourceRowsV3("care_welfare", [
    ["care.recipient_daily_life_fit","本人の生活・状態・希望・支援量への適合","fit_and_selection","T3","criteria_explanation"],
    ["care.family_coordination","家族の負担・連絡・役割・共同判断","fit_and_selection","T3","criteria_explanation"],
    ["care.care_manager_referral","ケアマネジャー・相談支援者から候補へつなぐ条件","candidate_discovery","T1","market_discovery"],
    ["care.service_start_assessment","見学・相談・認定・契約・利用開始の流れ","action_readiness","T4","action_readiness"],
    ["care.support_content_staff","支援内容・体制・職員・緊急対応・日常運用","trust_and_reputation","T6","trust_risk_diagnostic",["service","evidence_source","operational_requirement"]],
    ["care.continuation_change_exit","継続・変更・別サービス・終了・引継ぎ条件","action_readiness","T4","action_readiness"],
  ]),
  ...createRecoraTopicSourceRowsV3("education_school", [
    ["education.course_goal_fit","学習目的・レベル・進路・成果期待に合うコース","fit_and_selection","T3","criteria_explanation"],
    ["education.teacher_quality_fit","講師の専門性・指導方法・相性・サポート","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["education.curriculum_learning_method","カリキュラム・教材・授業形式・学習方法","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["education.trial_enrollment_flow","体験・説明会・申込・入学・必要手続き","action_readiness","T4","action_readiness"],
    ["education.tuition_total_cost","授業料・教材・入会・追加費用・支払条件","action_readiness","T4","action_readiness",["service","action_requirement","price_fee"]],
    ["education.schedule_location_online","時間・通学・オンライン・振替・欠席対応","fit_and_selection","T3","criteria_explanation"],
    ["education.continuation_progress_support","継続しやすさ・進捗確認・質問・退会・変更","trust_and_reputation","T3","trust_risk_diagnostic"],
  ]),
  ...createRecoraTopicSourceRowsV3("professional_service", [
    ["professional_service.client_problem_scope_fit","相談・依頼課題と対応範囲の適合","fit_and_selection","T3","criteria_explanation",["professional_person","comparison_criterion"]],
    ["professional_service.expertise_specialization","専門領域・資格・担当経験・対象業界","trust_and_reputation","T6","trust_risk_diagnostic",["professional_person","evidence_source","operational_requirement"]],
    ["professional_service.case_track_record","類似案件・実績・説明可能な成果根拠","trust_and_reputation","T5","trust_risk_diagnostic",["professional_person","evidence_source"]],
    ["professional_service.engagement_process","初回相談・提案・契約・実施・報告の流れ","action_readiness","T4","action_readiness",["professional_person","action_requirement"]],
    ["professional_service.fee_contract_scope","料金・見積・業務範囲・追加対応・解約","action_readiness","T4","action_readiness",["professional_person","action_requirement","price_fee","contract_condition"]],
    ["professional_service.collaboration_document_workflow","窓口・資料共有・顧客作業・レビュー・連絡方法","implementation_and_operation","T6","criteria_explanation",["professional_person","comparison_criterion","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("recruiting_hr", [
    ["recruiting.hiring_workflow_fit","募集・候補者管理・面接・採用決定業務への適合","fit_and_selection","T3","criteria_explanation"],
    ["recruiting.candidate_experience","応募者の使いやすさ・連絡・選考体験","trust_and_reputation","T6","trust_risk_diagnostic",["service","evidence_source","operational_requirement"]],
    ["recruiting.personal_data_privacy","履歴書・候補者情報・アクセス・保存・削除","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["recruiting.hr_system_integration","求人媒体・人事・カレンダー・連絡ツール連携","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["recruiting.recruiter_hiring_manager_operations","人事・現場責任者・面接担当間の運用","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
    ["recruiting.legal_fairness_compliance","採用法令・公平性・説明責任・監査可能性","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("real_estate", [
    ["realestate.rental_area_property_discovery","条件に合う地域・物件・仲介候補の発見","candidate_discovery","T1","market_discovery",["location_facility","solution_category"],{"applicability":{"structureSignalsAll":["real_estate_rental"]}}],
    ["realestate.rental_total_movein_cost","敷金・礼金・仲介・保証・更新等の総初期費用","action_readiness","T4","action_readiness",["location_facility","action_requirement","price_fee"],{"applicability":{"structureSignalsAll":["real_estate_rental"]}}],
    ["realestate.rental_application_screening","申込・審査・保証人・必要書類・入居時期","action_readiness","T4","action_readiness",["location_facility","action_requirement","contract_condition"],{"applicability":{"structureSignalsAll":["real_estate_rental"]}}],
    ["realestate.rental_contract_important_terms","契約期間・更新・解約・禁止事項・重要条件","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source","contract_condition"],{"applicability":{"structureSignalsAll":["real_estate_rental"]}}],
    ["realestate.rental_living_fit","通勤・生活・設備・家族・周辺環境への適合","fit_and_selection","T3","criteria_explanation",["location_facility","comparison_criterion"],{"applicability":{"structureSignalsAll":["real_estate_rental"]}}],
    ["realestate.purchase_area_property_discovery","購入目的に合う地域・物件・会社候補の発見","candidate_discovery","T1","market_discovery",["location_facility","solution_category"],{"applicability":{"structureSignalsAll":["real_estate_purchase_residential"]}}],
    ["realestate.purchase_budget_mortgage","購入予算・諸費用・住宅ローン・返済負担","pricing_and_value","T3","criteria_explanation",["location_facility","comparison_criterion","price_fee"],{"applicability":{"structureSignalsAll":["real_estate_purchase_residential"]}}],
    ["realestate.purchase_property_condition","建物・土地・設備・修繕・災害等の状態","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source"],{"applicability":{"structureSignalsAll":["real_estate_purchase_residential"]}}],
    ["realestate.purchase_contract_disclosure","重要事項・権利・契約条件・引渡し・保証","regulated_risk","T5","trust_risk_diagnostic",["location_facility","evidence_source","contract_condition"],{"applicability":{"structureSignalsAll":["real_estate_purchase_residential"]}}],
    ["realestate.purchase_household_future_fit","世帯・将来計画・通勤・教育・売却可能性への適合","fit_and_selection","T3","criteria_explanation",["location_facility","comparison_criterion"],{"applicability":{"structureSignalsAll":["real_estate_purchase_residential"]}}],
    ["realestate.sale_valuation_method","査定方法・根拠・価格幅・前提条件","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source"],{"applicability":{"structureSignalsAll":["real_estate_sale"]}}],
    ["realestate.sale_broker_comparison","仲介会社・売却方法・販売計画の比較","comparison","T2","market_comparison",["location_facility","comparison_criterion"],{"applicability":{"structureSignalsAll":["real_estate_sale"]}}],
    ["realestate.sale_fee_tax_timeline","仲介手数料・税・必要費用・期間・手続き","action_readiness","T4","action_readiness",["location_facility","action_requirement","price_fee"],{"applicability":{"structureSignalsAll":["real_estate_sale"]}}],
    ["realestate.sale_contract_strategy","媒介契約・売出条件・交渉・引渡し","action_readiness","T4","action_readiness",["location_facility","action_requirement","contract_condition"],{"applicability":{"structureSignalsAll":["real_estate_sale"]}}],
    ["realestate.sale_coowner_inheritance","共有名義・相続・代理・関係者同意","trust_and_reputation","T5","trust_risk_diagnostic",["location_facility","evidence_source"],{"applicability":{"structureSignalsAll":["real_estate_sale"]}}],
    ["realestate.professional_license_disclosure","宅建業免許・担当資格・登録・重要説明の確認点","regulated_risk","T5","trust_risk_diagnostic",["location_facility","evidence_source","qualification_registration"]],
    ["realestate.rental_property_area_specifics","間取り・設備・管理・周辺環境・生活条件","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"],{"applicability":{"structureSignalsAll":["real_estate_rental"]}}],
    ["realestate.purchase_due_diligence_specifics","建物・土地・修繕・災害・法的制約・将来利用の総合確認","trust_and_reputation","T6","trust_risk_diagnostic",["location_facility","evidence_source","operational_requirement"],{"applicability":{"structureSignalsAll":["real_estate_purchase_residential"]}}],
    ["realestate.sale_marketing_transaction_process","売出準備・販売計画・内覧・交渉・引渡しの固有プロセス","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"],{"applicability":{"structureSignalsAll":["real_estate_sale"]}}],
  ]),
  ...createRecoraTopicSourceRowsV3("finance_insurance", [
    ["finance.need_product_discovery","目的に対応する金融商品・保障・相談先の種類","candidate_discovery","T1","market_discovery",["product","service","professional_person","solution_category"]],
    ["finance.fee_risk_comparison","手数料・コスト・リスク・条件の比較","comparison","T2","market_comparison",["service","comparison_criterion","price_fee","risk_caution"]],
    ["finance.advisor_license_conflict","資格・登録・所属・報酬・利益相反","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","price_fee","qualification_registration"]],
    ["finance.suitability_risk_tolerance","目的・期間・損失許容・返済能力への適合","regulated_risk","T3","trust_risk_diagnostic",["service","evidence_source","price_fee","risk_caution"]],
    ["finance.application_disclosure","申込・本人確認・審査・重要説明・必要書類","action_readiness","T4","action_readiness",["service","action_requirement","price_fee","contract_condition"]],
    ["insurance.coverage_exclusions_claims","保障範囲・免責・給付条件・請求・支払対象外","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["finance.renewal_switching_cancellation","更新・見直し・乗り換え・解約・費用","continuation_and_switching","T3","market_comparison",["service","comparison_criterion","price_fee","contract_condition"]],
    ["insurance.coverage_structure_fit","契約者・被保険者・受取人・保障額・期間・特約の構造適合","trust_and_reputation","T6","trust_risk_diagnostic",["service","evidence_source","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("travel_hospitality", [
    ["travel.destination_accommodation_discovery","目的・地域・日程に合う旅行先・宿泊・体験候補","candidate_discovery","T1","market_discovery",["location_facility","solution_category"]],
    ["travel.itinerary_experience_fit","旅程・移動・滞在・同行者・目的への適合","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"]],
    ["travel.group_business_requirements","団体・出張・行事の人数・部屋・請求・調整条件","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"],{"applicability":{"structureSignalsAll":["group_or_business_travel"]}}],
    ["travel.booking_price_change_cancellation","予約総額・支払・変更・取消・返金条件","continuation_and_switching","T4","action_readiness",["location_facility","action_requirement","price_fee","contract_condition"]],
    ["travel.accessibility_safety_documents","バリアフリー・安全・保険・渡航・本人確認書類","regulated_risk","T5","trust_risk_diagnostic",["location_facility","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("restaurant_food_catering", [
    ["food.dining_cuisine_discovery","目的・料理・地域・予算に合う店舗・食事候補","candidate_discovery","T1","market_discovery",["location_facility","solution_category"]],
    ["food.reservation_group_conditions","予約・人数・席・コース・支払・キャンセル","action_readiness","T4","action_readiness",["location_facility","action_requirement"]],
    ["food.allergy_dietary_safety","アレルギー・食事制限・原材料・衛生対応","regulated_risk","T5","trust_risk_diagnostic",["location_facility","evidence_source","risk_caution"]],
    ["food.catering_order_delivery","ケータリング数量・会場・配送・設営・法人発注条件","action_readiness","T6","action_readiness",["location_facility","action_requirement","operational_requirement"]],
    ["food.menu_occasion_experience_fit","料理・メニュー・利用目的・人数・時間帯・店内体験への適合","implementation_and_operation","T6","criteria_explanation",["location_facility","comparison_criterion","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("beauty_wellness", [
    ["beauty.service_goal_fit","美容・運動・ウェルネス目的への施術・サービス適合","fit_and_selection","T3","criteria_explanation"],
    ["beauty.provider_qualification_risk","担当者・資格・説明・注意点・向かない条件","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","qualification_registration","risk_caution"]],
    ["beauty.booking_pricing_course","予約・初回料金・コース・追加費用・キャンセル","action_readiness","T4","action_readiness"],
    ["beauty.continuation_aftercare","継続頻度・アフターケア・休止・変更・解約","trust_and_reputation","T3","trust_risk_diagnostic"],
    ["beauty.treatment_service_experience","施術・サービス内容・所要時間・担当・設備・利用体験","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("construction_home_service", [
    ["home_service.contractor_discovery","修理・施工・改修内容に対応できる事業者候補","candidate_discovery","T1","market_discovery",["company","service","solution_category"]],
    ["home_service.site_scope_quote","現場条件・作業範囲・見積内訳・追加工事","action_readiness","T4","action_readiness"],
    ["home_service.schedule_access_preparation","日程・立会い・搬入・近隣対応・事前準備","action_readiness","T4","action_readiness"],
    ["home_service.license_insurance_safety","許可・資格・保険・安全・下請・本人確認","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","qualification_registration","risk_caution"]],
    ["home_service.warranty_followup","工事・作業後の保証・再対応・保守・トラブル窓口","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["home_service.work_scope_site_conditions","建物・設備・現場条件・作業範囲・施工方法・制約への適合","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("manufacturing_industrial", [
    ["manufacturing.production_problem_solution","生産・品質・設備・工数課題に合う解決手段","candidate_discovery","T1","market_discovery",["product","solution_category"]],
    ["manufacturing.technical_spec_performance","性能・精度・能力・材質・環境・互換性","implementation_and_operation","T6","criteria_explanation",["company","comparison_criterion","operational_requirement"]],
    ["manufacturing.capex_total_cost","設備価格・工事・運用・保守・回収期間","pricing_and_value","T3","criteria_explanation",["company","comparison_criterion","price_fee"]],
    ["manufacturing.supplier_procurement","供給者・見積・納期・契約・調達条件","action_readiness","T4","action_readiness",["company","action_requirement","contract_condition"]],
    ["manufacturing.operator_maintenance","操作・教育・保守・部品・停止時間","implementation_and_operation","T6","criteria_explanation",["company","comparison_criterion","operational_requirement"]],
    ["manufacturing.quality_safety_compliance","品質基準・安全・規格・検査・記録","regulated_risk","T5","trust_risk_diagnostic",["company","evidence_source","risk_caution"]],
  ]),
  ...createRecoraTopicSourceRowsV3("logistics_supply_chain", [
    ["logistics.operations_problem_solution","配送・倉庫・在庫・出荷課題に合う候補","candidate_discovery","T1","market_discovery",["company","solution_category"]],
    ["logistics.provider_3pl_comparison","物流会社・3PL・システム・内製の比較","comparison","T2","market_comparison",["company","comparison_criterion"]],
    ["logistics.pricing_sla","料金・最低数量・納期・SLA・追加費用","action_readiness","T4","action_readiness",["company","action_requirement"]],
    ["logistics.warehouse_dispatch_operations","入出庫・保管・配車・繁忙期・現場運用","implementation_and_operation","T6","criteria_explanation",["company","comparison_criterion","operational_requirement"]],
    ["logistics.tracking_integration_data","追跡・在庫連携・API・データ精度・可視化","implementation_and_operation","T6","criteria_explanation",["company","comparison_criterion","operational_requirement"]],
    ["logistics.continuity_claims_exceptions","災害・遅延・破損・補償・例外時対応","trust_and_reputation","T5","trust_risk_diagnostic",["company","evidence_source"]],
  ]),
  ...createRecoraTopicSourceRowsV3("automotive_mobility", [
    ["automotive.vehicle_mobility_discovery","購入・利用・移動目的に合う車両・サービス候補","candidate_discovery","T1","market_discovery",["product","solution_category"]],
    ["automotive.purchase_finance","車両価格・ローン・リース・維持費・契約","action_readiness","T4","action_readiness",["service","action_requirement","price_fee"]],
    ["automotive.repair_maintenance_quote","修理・点検・部品・見積・作業範囲","action_readiness","T4","action_readiness"],
    ["automotive.safety_warranty_history","安全・保証・整備履歴・事故歴・リコール","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["automotive.fleet_operations_lifecycle","法人車両の稼働・安全・保守・更新・処分","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"],{"applicability":{"audienceScopesAny":["b2b","both"]}}],
    ["automotive.vehicle_use_ownership_fit","車両用途・運転者・利用頻度・保管・所有形態への適合","implementation_and_operation","T6","criteria_explanation",["product","comparison_criterion","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("media_content_advertising", [
    ["media.audience_content_discovery","読者・視聴者が目的に合う媒体・コンテンツを探す","candidate_discovery","T1","market_discovery"],
    ["media.paid_subscription_value","有料購読・会員特典・料金・継続価値","continuation_and_switching","T3","criteria_explanation",["service","comparison_criterion","contract_condition"]],
    ["media.advertiser_media_fit","広告主の対象顧客・目的・掲載面・成果条件への適合","fit_and_selection","T3","criteria_explanation"],
    ["media.agency_media_comparison","代理店による媒体・広告商品・条件比較","comparison","T2","market_comparison"],
    ["media.creator_contributor_terms","外部制作者・投稿者の契約・報酬・権利・運用","action_readiness","T4","action_readiness",["service","action_requirement","contract_condition"]],
    ["media.brand_safety_measurement","掲載環境・ブランド毀損・品質・測定・透明性","regulated_risk","T5","trust_risk_diagnostic",["service","evidence_source","risk_caution"]],
    ["media.audience_advertiser_creator_ecosystem","読者価値・広告主価値・制作者条件・媒体運営の関係","implementation_and_operation","T6","criteria_explanation",["service","comparison_criterion","operational_requirement"]],
  ]),
  ...createRecoraTopicSourceRowsV3("publisher_content", [
    ["publisher.content_authority_quality","内容の専門性・正確性・独自性・更新性","trust_and_reputation","T5","trust_risk_diagnostic"],
    ["publisher.editorial_transparency_sources","編集方針・著者・訂正・広告表示・情報源","citation_and_evidence","T5","forced_citation_validation",["service"]],
    ["publisher.membership_retention_experience","会員価値・閲覧体験・継続・解約・利用条件","fit_and_selection","T3","criteria_explanation"],
  ]),
] as const satisfies readonly RecoraTopicBlueprintSourceRowV3[];
