import type { RecoraPersonaBlueprintSourceRowV3 } from "./measurement-persona-catalog";

export const RECORA_PERSONA_INDUSTRY_BLUEPRINT_ROWS_V3: readonly RecoraPersonaBlueprintSourceRowV3[] = [
  ["enterprise_it_security", "enterprise.it_strategy_owner", "IT方針・標準化・投資優先度を決める責任者", ["C3"], "decision_owner", "prospective_customer", "selectable", ["enterprise_it_security"]],
  ["enterprise_it_security", "enterprise.solution_architect_evaluator", "システム構成・連携・実装可能性を評価する担当者", ["C2", "C6"], "evaluator", "prospective_customer", "selectable", ["enterprise_it_security"]],
  ["enterprise_it_security", "enterprise.security_reviewer", "セキュリティ・アクセス・データ保護を審査する担当者", ["C6"], "reviewer", "prospective_customer", "selectable", ["enterprise_it_security"]],
  ["enterprise_it_security", "enterprise.system_administrator", "導入後に設定・権限・日常運用を担う管理者", ["C4"], "operator", "end_user_or_beneficiary", "selectable", ["enterprise_it_security"]],
  ["enterprise_it_security", "enterprise.vendor_risk_reviewer", "ベンダーリスク・継続性を審査する担当者", ["C6"], "reviewer", "prospective_customer", "selectable", ["enterprise_it_security"]],
  ["commerce_product", "commerce.product_need_user", "商品を必要とし利用目的を持つ本人", ["C1"], "need_owner", "prospective_customer", "selectable", ["commerce_single_purchase", "commerce_subscription", "commerce_gift"]],
  ["commerce_product", "commerce.product_comparator", "複数商品・ブランドを比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["commerce_single_purchase", "commerce_subscription", "commerce_gift"]],
  ["commerce_product", "commerce.purchase_owner", "購入する商品・販売先・支払いを決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["commerce_single_purchase", "commerce_subscription", "commerce_gift"]],
  ["commerce_product", "commerce.product_recipient", "商品を実際に受け取り利用する人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["commerce_single_purchase", "commerce_subscription", "commerce_gift"]],
  ["commerce_product", "commerce.repeat_purchase_user", "再購入・継続・乗り換えを判断する利用者", ["C8"], "existing_user", "current_customer", "selectable", ["commerce_single_purchase", "commerce_subscription", "commerce_gift"]],
  ["commerce_product", "commerce.gift_purchaser", "ギフトを選び購入する人", ["C3", "C7"], "decision_owner", "payer_or_sponsor", "selectable", ["commerce_single_purchase", "commerce_subscription", "commerce_gift"]],
  ["local_facility", "local.nearby_need_owner", "特定地域で利用先を必要とする本人", ["C1"], "need_owner", "prospective_customer", "selectable", ["local_facility", "multi_location_consumer_brand", "franchise_consumer_brand"]],
  ["local_facility", "local.provider_comparator", "複数の近隣店舗・施設を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["local_facility", "multi_location_consumer_brand", "franchise_consumer_brand"]],
  ["local_facility", "local.booking_decider", "予約・来店先を決める人", ["C3"], "decision_owner", "prospective_customer", "selectable", ["local_facility", "multi_location_consumer_brand", "franchise_consumer_brand"]],
  ["local_facility", "local.service_recipient", "店舗・施設サービスを実際に受ける人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["local_facility", "multi_location_consumer_brand", "franchise_consumer_brand"]],
  ["healthcare_clinic", "healthcare.patient_need_owner", "相談・診療・施術の必要性を感じている本人", ["C1"], "need_owner", "prospective_customer", "selectable", ["adult_healthcare"]],
  ["healthcare_clinic", "healthcare.provider_evaluator", "医療機関・医師・施術候補を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["adult_healthcare"]],
  ["healthcare_clinic", "healthcare.booking_decider", "初回相談・予約先を決める人", ["C3"], "decision_owner", "prospective_customer", "selectable", ["adult_healthcare"]],
  ["healthcare_clinic", "healthcare.patient_recipient", "相談・診療・施術を受ける患者", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["adult_healthcare"]],
  ["healthcare_clinic", "healthcare.referring_professional", "医療・支援の専門家として受診先を紹介する人", ["C5"], "recommender", "influencer_or_referrer", "selectable", ["adult_healthcare"]],
  ["care_welfare", "care.care_recipient", "介護・福祉サービスを受ける本人", ["C1", "C4"], "recipient", "end_user_or_beneficiary", "selectable", ["care_welfare"]],
  ["care_welfare", "care.family_need_coordinator", "本人の生活課題を整理し家族内で選択を進める人", ["C1", "C7"], "proxy", "influencer_or_referrer", "selectable", ["care_welfare"]],
  ["care_welfare", "care.care_manager_referrer", "ケアマネジャー・相談支援者として候補を紹介する人", ["C2", "C5"], "recommender", "influencer_or_referrer", "selectable", ["care_welfare"]],
  ["care_welfare", "care.service_start_decider", "契約・利用開始を決める人", ["C3", "C7"], "decision_owner", "payer_or_sponsor", "selectable", ["care_welfare"]],
  ["care_welfare", "care.frontline_care_worker", "現場で支援を実施しサービス適合を判断する人", ["C4"], "provider", "prospective_customer", "conditional", ["care_welfare"]],
  ["education_school", "education.learner_need_owner", "学習目的・課題を持つ受講希望者・学習者", ["C1"], "need_owner", "prospective_customer", "selectable", ["adult_education", "child_education", "corporate_training"]],
  ["education_school", "education.course_evaluator", "コース・スクール・学習方法を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["adult_education", "child_education", "corporate_training"]],
  ["education_school", "education.enrollment_decider", "体験・申込・契約を決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["adult_education", "child_education", "corporate_training"]],
  ["education_school", "education.active_learner", "授業・レッスンを実際に受ける学習者", ["C4"], "end_user", "end_user_or_beneficiary", "selectable", ["adult_education", "child_education", "corporate_training"]],
  ["education_school", "education.teacher_school_recommender", "教師・学校・進路支援者として学習先を推薦する人", ["C5"], "recommender", "influencer_or_referrer", "selectable", ["adult_education", "child_education", "corporate_training"]],
  ["professional_service", "professional.client_problem_owner", "専門的な相談・依頼が必要な課題を持つ顧客", ["C1"], "need_owner", "prospective_customer", "selectable", ["professional_service_b2b"]],
  ["professional_service", "professional.provider_evaluator", "事務所・専門家を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["professional_service_b2b"]],
  ["professional_service", "professional.engagement_decision_owner", "依頼・予算・顧問・委任契約を決める責任者", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["professional_service_b2b"]],
  ["professional_service", "professional.operational_liaison", "日常の連絡・資料共有・実務調整を担う窓口", ["C4"], "operator", "end_user_or_beneficiary", "selectable", ["professional_service_b2b"]],
  ["recruiting_hr", "recruiting.hiring_problem_owner", "採用課題を持つ人事・採用責任者", ["C1"], "need_owner", "prospective_customer", "selectable", ["recruiting_employer_saas"]],
  ["recruiting_hr", "recruiting.solution_evaluator", "ATS・採用支援サービスを比較する担当者", ["C2"], "evaluator", "prospective_customer", "selectable", ["recruiting_employer_saas"]],
  ["recruiting_hr", "recruiting.adoption_decision_owner", "導入・予算・契約を決める責任者", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["recruiting_employer_saas"]],
  ["recruiting_hr", "recruiting.recruiter_operator", "候補者管理・面接調整・現場連携を行う担当者", ["C4"], "operator", "end_user_or_beneficiary", "selectable", ["recruiting_employer_saas"]],
  ["recruiting_hr", "recruiting.hiring_manager_stakeholder", "配属部門側で要件・評価・採用結果に関わる現場責任者", ["C5"], "champion", "prospective_customer", "selectable", ["recruiting_employer_saas"]],
  ["real_estate_rental", "rental.moving_need_owner", "転居・住み替えの必要性を持つ本人", ["C1"], "need_owner", "prospective_customer", "selectable", ["real_estate_rental"]],
  ["real_estate_rental", "rental.property_agent_evaluator", "物件・地域・仲介会社を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["real_estate_rental"]],
  ["real_estate_rental", "rental.application_contract_decider", "問い合わせ・内見・申込・契約を決める人", ["C3"], "decision_owner", "prospective_customer", "selectable", ["real_estate_rental"]],
  ["real_estate_rental", "rental.actual_tenant", "物件へ実際に入居し生活する人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["real_estate_rental"]],
  ["real_estate_purchase", "homepurchase.home_need_owner", "住宅購入・住み替えの必要性を持つ本人・世帯", ["C1"], "need_owner", "prospective_customer", "selectable", ["real_estate_purchase_residential"]],
  ["real_estate_purchase", "homepurchase.property_evaluator", "物件・地域・販売会社・仲介会社を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["real_estate_purchase_residential"]],
  ["real_estate_purchase", "homepurchase.mortgage_contract_decider", "購入・資金計画・住宅ローン・契約を決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["real_estate_purchase_residential"]],
  ["real_estate_purchase", "homepurchase.household_occupant", "住宅へ実際に居住し生活条件を評価する人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["real_estate_purchase_residential"]],
  ["real_estate_sale", "homesale.disposition_need_owner", "売却・資産整理の必要性を持つ所有者", ["C1"], "need_owner", "prospective_customer", "selectable", ["real_estate_sale"]],
  ["real_estate_sale", "homesale.broker_valuation_evaluator", "仲介会社・査定・売却方法を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["real_estate_sale"]],
  ["real_estate_sale", "homesale.sale_contract_decider", "売出価格・媒介・契約条件を決める所有者・責任者", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["real_estate_sale"]],
  ["real_estate_sale", "homesale.co_owner_decision_member", "共有所有者として売却判断に関わる人", ["C7"], "proxy", "influencer_or_referrer", "selectable", ["real_estate_sale"]],
  ["real_estate_sale", "homesale.estate_inheritance_stakeholder", "相続関係者として売却判断に関わる人", ["C7"], "proxy", "influencer_or_referrer", "selectable", ["real_estate_sale"]],
  ["finance_insurance", "insurance.coverage_need_owner", "保険加入・保障見直しの必要性を持つ本人", ["C1"], "need_owner", "prospective_customer", "selectable", ["insurance"]],
  ["finance_insurance", "insurance.policyholder", "保険契約を保有し契約条件を判断する人", ["C3", "C8"], "decision_owner", "payer_or_sponsor", "selectable", ["insurance"]],
  ["finance_insurance", "insurance.insured_person", "保障・サービスの対象となる本人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["insurance"]],
  ["finance_insurance", "insurance.beneficiary", "給付・保険金・便益を受ける人", ["C4", "C7"], "recipient", "end_user_or_beneficiary", "selectable", ["insurance"]],
  ["finance_insurance", "insurance.claimant", "給付・保険金を請求する人", ["C4", "C7"], "proxy", "current_customer", "selectable", ["insurance"]],
  ["finance_insurance", "finance.investment_account_owner", "投資方針・口座・リスク負担を決める本人", ["C1", "C3"], "decision_owner", "payer_or_sponsor", "selectable", ["insurance"]],
  ["finance_insurance", "finance.borrower", "融資・ローンを利用し返済責任を負う人", ["C1", "C3"], "decision_owner", "payer_or_sponsor", "selectable", ["insurance"]],
  ["finance_insurance", "finance.guarantor_collateral_provider", "保証・担保提供により別の責任を負う人", ["C6", "C7"], "ratifier", "payer_or_sponsor", "selectable", ["insurance"]],
  ["travel_hospitality", "travel.traveler_need_owner", "旅行・宿泊の目的と条件を持つ本人", ["C1"], "need_owner", "prospective_customer", "selectable", ["individual_travel", "group_or_business_travel"]],
  ["travel_hospitality", "travel.booking_decider", "宿泊・交通・ツアーの予約と支払いを決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["individual_travel", "group_or_business_travel"]],
  ["travel_hospitality", "travel.trip_recipient", "旅行・宿泊・体験を実際に利用する人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["individual_travel", "group_or_business_travel"]],
  ["travel_hospitality", "travel.group_event_planner", "家族旅行・団体旅行・出張を取りまとめる人", ["C5", "C7"], "proxy", "influencer_or_referrer", "selectable", ["individual_travel", "group_or_business_travel"]],
  ["restaurant_food_catering", "food.diner_recipient", "食事・飲食サービスを実際に利用する人", ["C1", "C4"], "recipient", "end_user_or_beneficiary", "selectable", []],
  ["restaurant_food_catering", "food.reservation_order_decider", "店舗予約・注文・支払いを決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", []],
  ["restaurant_food_catering", "food.group_meal_organizer", "家族・友人・会食の条件を取りまとめる人", ["C5", "C7"], "proxy", "influencer_or_referrer", "selectable", []],
  ["restaurant_food_catering", "food.catering_event_buyer", "法人・行事向けケータリングを選定・発注する人", ["C2", "C3"], "payer", "payer_or_sponsor", "selectable", []],
  ["beauty_wellness", "beauty.service_need_owner", "美容・ウェルネスサービスを必要とする本人", ["C1"], "need_owner", "prospective_customer", "selectable", []],
  ["beauty_wellness", "beauty.provider_evaluator", "店舗・施術・担当者を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", []],
  ["beauty_wellness", "beauty.booking_decider", "予約・コース・支払いを決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", []],
  ["beauty_wellness", "beauty.service_recipient", "施術・トレーニング・サービスを受ける人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", []],
  ["construction_home_service", "home_service.occupant_need_owner", "住居利用者として住宅・設備の課題を持つ人", ["C1"], "need_owner", "prospective_customer", "selectable", ["urgent_service"]],
  ["construction_home_service", "home_service.property_owner_need_owner", "物件所有者として修理・改修の必要性を持つ人", ["C1"], "need_owner", "payer_or_sponsor", "selectable", ["urgent_service"]],
  ["construction_home_service", "home_service.contractor_evaluator", "施工・修理・訪問事業者を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["urgent_service"]],
  ["construction_home_service", "home_service.quote_contract_decider", "見積もり・依頼・契約・支払いを決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["urgent_service"]],
  ["construction_home_service", "home_service.site_contact_recipient", "現場立会い・作業調整・サービス受領を担う人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", ["urgent_service"]],
  ["construction_home_service", "home_service.emergency_decider", "故障・事故・緊急時に連絡先と費用を判断する人", ["C3", "C7"], "decision_owner", "payer_or_sponsor", "selectable", ["urgent_service"]],
  ["manufacturing_industrial", "manufacturing.plant_problem_owner", "生産・品質・設備上の課題を持つ工場・部門責任者", ["C1"], "need_owner", "prospective_customer", "selectable", ["manufacturing_capex"]],
  ["manufacturing_industrial", "manufacturing.technical_spec_evaluator", "仕様・性能・安全・保守性を評価する技術担当者", ["C2", "C6"], "evaluator", "prospective_customer", "selectable", ["manufacturing_capex"]],
  ["manufacturing_industrial", "manufacturing.capex_decision_owner", "設備投資・更新・予算を判断する責任者", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["manufacturing_capex"]],
  ["manufacturing_industrial", "manufacturing.procurement_buyer", "仕入先・価格・納期・契約を管理する調達担当者", ["C3", "C6"], "ratifier", "payer_or_sponsor", "selectable", ["manufacturing_capex"]],
  ["manufacturing_industrial", "manufacturing.operator_maintenance_user", "設備を使い保守・運用を担う現場担当者", ["C4"], "operator", "end_user_or_beneficiary", "selectable", ["manufacturing_capex"]],
  ["logistics_supply_chain", "logistics.operations_problem_owner", "配送・倉庫・在庫・SLAの課題を持つ責任者", ["C1"], "need_owner", "prospective_customer", "selectable", ["logistics_shipper_buying"]],
  ["logistics_supply_chain", "logistics.solution_evaluator", "物流会社・3PL・システムを比較する担当者", ["C2"], "evaluator", "prospective_customer", "selectable", ["logistics_shipper_buying"]],
  ["logistics_supply_chain", "logistics.contract_sla_decider", "料金・契約・サービス水準を決める責任者", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["logistics_shipper_buying"]],
  ["logistics_supply_chain", "logistics.dispatch_warehouse_operator", "配車・倉庫・在庫・出荷を運用する人", ["C4"], "operator", "end_user_or_beneficiary", "selectable", ["logistics_shipper_buying"]],
  ["logistics_supply_chain", "logistics.integration_data_reviewer", "連携・追跡・データ管理を審査する担当者", ["C6"], "reviewer", "prospective_customer", "selectable", ["logistics_shipper_buying"]],
  ["automotive_mobility", "automotive.vehicle_owner_need_owner", "車両所有者として購入・修理・点検の課題を持つ人", ["C1"], "need_owner", "prospective_customer", "selectable", []],
  ["automotive_mobility", "automotive.driver_mobility_need_owner", "運転者・移動利用者として課題を持つ人", ["C1"], "need_owner", "end_user_or_beneficiary", "selectable", []],
  ["automotive_mobility", "automotive.dealer_repair_evaluator", "販売店・修理工場・車両候補を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", []],
  ["automotive_mobility", "automotive.purchase_decider", "車両購入・契約・支払いを決める人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", []],
  ["automotive_mobility", "automotive.repair_authorization_decider", "修理・点検の依頼と費用を承認する人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", []],
  ["automotive_mobility", "automotive.driver_vehicle_user", "車両・移動サービスを実際に利用する人", ["C4"], "end_user", "end_user_or_beneficiary", "selectable", []],
  ["automotive_mobility", "automotive.fleet_manager", "法人車両の調達・稼働・安全・更新を管理する責任者", ["C3", "C4"], "operator", "prospective_customer", "selectable", []],
  ["media_content_advertising", "media.reader_viewer", "記事・動画・情報を利用する読者・視聴者", ["C1", "C4"], "recipient", "end_user_or_beneficiary", "selectable", ["media_brand"]],
  ["media_content_advertising", "media.paid_subscriber", "有料購読・会員契約と継続を判断する人", ["C3", "C8"], "existing_user", "current_customer", "selectable", ["media_brand"]],
  ["media_content_advertising", "media.external_creator_contributor", "外部からコンテンツ制作・投稿・情報提供を行う人", ["C4", "C5"], "creator", "partner_or_intermediary", "selectable", ["media_brand"]],
  ["media_content_advertising", "media.internal_content_operator", "媒体内部で制作・投稿運用を担う担当者", ["C4"], "operator", "prospective_customer", "conditional", ["media_brand"]],
  ["media_content_advertising", "media.advertiser_buyer", "広告・協賛・掲載費用を判断する広告主", ["C3"], "payer", "payer_or_sponsor", "selectable", ["media_brand"]],
  ["media_content_advertising", "media.agency_media_planner", "広告主に代わって媒体を比較・選定する代理店担当者", ["C2", "C5"], "advisor", "partner_or_intermediary", "selectable", ["media_brand"]],
  ["media_content_advertising", "media.publisher_editorial_owner", "媒体方針・編集品質・収益を管理する運営責任者", ["C3", "C5"], "decision_owner", "prospective_customer", "conditional", ["media_brand"]]
];