import type { RecoraPersonaBlueprintSourceRowV3 } from "./measurement-persona-catalog";

export const RECORA_PERSONA_COMMON_BLUEPRINT_ROWS_V3: readonly RecoraPersonaBlueprintSourceRowV3[] = [
  ["b2b_buying_group", "b2b.problem_owner", "業務課題を直接持つ担当者", ["C1"], "need_owner", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.internal_champion", "社内で導入の合意形成を進める推進者", ["C5"], "champion", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.solution_evaluator", "候補を比較しShortlistを作る評価担当者", ["C2"], "evaluator", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.strategic_decision_owner", "戦略適合と導入可否を最終判断する責任者", ["C3"], "decision_owner", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.economic_buyer", "予算・費用対効果・契約規模を判断する責任者", ["C3"], "payer", "payer_or_sponsor", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.end_user", "製品・サービスを実際に利用する担当者", ["C4"], "end_user", "end_user_or_beneficiary", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.operations_owner", "日々の運用・業務プロセスを管理する責任者", ["C4"], "operator", "end_user_or_beneficiary", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.implementation_change_owner", "導入・移行・教育・定着を担う責任者", ["C4", "C5"], "operator", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.technical_reviewer", "技術仕様・連携・実装可能性を審査する担当者", ["C6"], "reviewer", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.security_privacy_reviewer", "セキュリティ・個人情報・データ管理を審査する担当者", ["C6"], "reviewer", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.procurement_ratifier", "調達手続き・価格・取引条件を承認する担当者", ["C6"], "ratifier", "payer_or_sponsor", "selectable", ["b2b_buying_group"]],
  ["b2b_buying_group", "b2b.legal_compliance_blocker", "法務・規制・契約リスクを確認し停止できる担当者", ["C6"], "blocker", "prospective_customer", "selectable", ["b2b_buying_group"]],
  ["b2c_decision_unit", "b2c.need_owner", "課題・目的・便益を直接持つ本人", ["C1"], "need_owner", "prospective_customer", "selectable", []],
  ["b2c_decision_unit", "b2c.option_evaluator", "複数候補を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", []],
  ["b2c_decision_unit", "b2c.purchase_decider", "購入・予約・申込先を決める人", ["C3"], "decision_owner", "prospective_customer", "selectable", []],
  ["b2c_decision_unit", "b2c.payer", "料金を実際に負担する人", ["C3", "C7"], "payer", "payer_or_sponsor", "selectable", []],
  ["b2c_decision_unit", "b2c.actual_user", "商品・サービスを実際に使う人", ["C4"], "end_user", "end_user_or_beneficiary", "selectable", []],
  ["b2c_decision_unit", "b2c.service_recipient", "施術・相談・教育・支援を実際に受ける人", ["C4"], "recipient", "end_user_or_beneficiary", "selectable", []],
  ["b2c_decision_unit", "b2c.recommender_influencer", "本人や家族へ候補を推薦する人", ["C5"], "recommender", "influencer_or_referrer", "selectable", []],
  ["b2c_decision_unit", "b2c.alternate_payer", "利用者とは別に支払いを担う人", ["C7"], "payer", "payer_or_sponsor", "selectable", []],
  ["b2c_decision_unit", "b2c.group_occasion_planner", "家族・グループ・行事の選択を取りまとめる人", ["C5", "C7"], "proxy", "influencer_or_referrer", "selectable", []],
  ["lifecycle_experience", "lifecycle.first_time_explorer", "初めてカテゴリや候補を探す状態", ["C1", "C2"], "existing_user", "prospective_customer", "modifier", []],
  ["lifecycle_experience", "lifecycle.trial_user", "試用・体験中で本契約を判断する状態", ["C2", "C4"], "existing_user", "current_customer", "modifier", []],
  ["lifecycle_experience", "lifecycle.active_user", "現在利用中で実体験を持つ状態", ["C4"], "existing_user", "current_customer", "modifier", []],
  ["lifecycle_experience", "lifecycle.failed_prior_choice_researcher", "過去の選択失敗を踏まえて再検討する状態", ["C1", "C2"], "existing_user", "current_customer", "modifier", []],
  ["lifecycle_experience", "lifecycle.renewal_decider", "更新・継続契約を判断する状態", ["C8"], "existing_user", "current_customer", "modifier", []],
  ["lifecycle_experience", "lifecycle.cancellation_decider", "休止・解約を判断する状態", ["C8"], "existing_user", "current_customer", "modifier", []],
  ["lifecycle_experience", "lifecycle.switching_evaluator", "他社・他商品への乗り換えを比較する状態", ["C2", "C8"], "existing_user", "current_customer", "modifier", []],
  ["family_proxy_care", "family.need_interpreter", "本人の状況・希望を整理して候補探しを支える家族", ["C1", "C7"], "proxy", "influencer_or_referrer", "selectable", []],
  ["family_proxy_care", "family.guardian_decision_maker", "未成年者等の選択・契約を決める保護者", ["C3", "C7"], "proxy", "payer_or_sponsor", "selectable", []],
  ["family_proxy_care", "family.caregiver_supporter", "日常的な介護・支援の立場から選択に関わる人", ["C4", "C7"], "proxy", "influencer_or_referrer", "selectable", []],
  ["family_proxy_care", "family.formal_proxy_decision_maker", "正式な代理権限を持って判断する人", ["C3", "C7"], "proxy", "payer_or_sponsor", "selectable", []],
  ["family_proxy_care", "family.co_decision_member", "本人と共同で判断する家族・同居人", ["C5", "C7"], "proxy", "influencer_or_referrer", "selectable", []],
  ["agency_consultant_partner", "agency.owner_buyer", "代理店・支援会社側で導入や仕入れを決める責任者", ["C3"], "decision_owner", "partner_or_intermediary", "conditional", ["agency_delivery"]],
  ["agency_consultant_partner", "agency.operator", "顧客向け提供・運用を実際に行う担当者", ["C4"], "operator", "partner_or_intermediary", "conditional", ["agency_delivery"]],
  ["agency_consultant_partner", "agency.client_decision_owner", "最終顧客企業側で契約・採用を決める責任者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["agency_delivery"]],
  ["agency_consultant_partner", "agency.client_evaluator", "最終顧客企業側で候補や提案を評価する担当者", ["C2"], "evaluator", "prospective_customer", "conditional", ["agency_delivery"]],
  ["agency_consultant_partner", "agency.external_advisor", "顧客へ第三者として候補を推薦する専門家", ["C5"], "advisor", "influencer_or_referrer", "conditional", ["agency_delivery", "real_estate_sale"]],
  ["agency_consultant_partner", "agency.implementation_partner", "導入・設定・定着を支援する外部パートナー", ["C4", "C5"], "provider", "partner_or_intermediary", "conditional", ["agency_delivery"]],
  ["b2b2c", "b2b2c.sponsor_decision_owner", "組織側で導入・費用・契約を決める責任者", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["b2b2c"]],
  ["b2b2c", "b2b2c.client_operator", "組織側でサービス運用や利用者対応を担う人", ["C4"], "operator", "prospective_customer", "selectable", ["b2b2c"]],
  ["b2b2c", "b2b2c.end_beneficiary", "サービスを使い便益を受ける最終利用者", ["C1", "C4"], "recipient", "end_user_or_beneficiary", "selectable", ["b2b2c"]],
  ["b2b2c", "b2b2c.outcome_accountability_owner", "最終利用者への成果・品質に責任を持つ人", ["C5", "C6"], "reviewer", "prospective_customer", "selectable", ["b2b2c"]],
  ["marketplace_demand", "marketplace.demand_need_owner", "Marketplaceで商品・サービスを探す需要側の当事者", ["C1"], "need_owner", "demand_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_demand", "marketplace.demand_listing_comparator", "複数の出品・提供者を比較する需要側利用者", ["C2"], "evaluator", "demand_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_demand", "marketplace.demand_transaction_decider", "購入・予約・発注を決める需要側利用者", ["C3"], "decision_owner", "demand_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_demand", "marketplace.demand_service_recipient", "取引後に商品・サービスを実際に受ける人", ["C4"], "recipient", "demand_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_supply", "marketplace.supply_business_owner", "出品・参加の事業判断を行う供給側責任者", ["C1", "C3"], "decision_owner", "supply_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_supply", "marketplace.supply_onboarding_decider", "手数料・規約を確認し参加を決める人", ["C3"], "decision_owner", "supply_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_supply", "marketplace.supply_platform_evaluator", "供給側として複数Marketplaceを比較する担当者", ["C2"], "evaluator", "supply_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_supply", "marketplace.supply_listing_operator", "商品・在庫・予約・掲載情報を運用する担当者", ["C4"], "operator", "supply_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_supply", "marketplace.supply_service_fulfiller", "商品・サービスを実際に提供する人", ["C4"], "provider", "supply_side_participant", "selectable", ["marketplace_brand"]],
  ["marketplace_operator", "marketplace.operator_business_owner", "Marketplace全体の事業責任者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["marketplace_operator_customer"]],
  ["marketplace_operator", "marketplace.demand_growth_owner", "購入・利用側の獲得と活性化を担う人", ["C5"], "champion", "prospective_customer", "conditional", ["marketplace_operator_customer"]],
  ["marketplace_operator", "marketplace.supply_growth_owner", "出品・提供側の獲得と定着を担う人", ["C5"], "champion", "prospective_customer", "conditional", ["marketplace_operator_customer"]],
  ["marketplace_operator", "marketplace.trust_safety_owner", "審査・不正・品質・安全性を管理する担当者", ["C6"], "reviewer", "prospective_customer", "conditional", ["marketplace_operator_customer"]],
  ["marketplace_operator", "marketplace.support_dispute_owner", "問い合わせ・紛争・取引後対応を管理する人", ["C4", "C6"], "operator", "prospective_customer", "conditional", ["marketplace_operator_customer"]],
  ["multi_location_hq", "multilocation.hq_strategy_owner", "本部で全拠点の方針・導入を決める責任者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["multi_location_customer_organization"]],
  ["multi_location_hq", "multilocation.hq_operations_owner", "全拠点の運用標準化を担う責任者", ["C4"], "operator", "prospective_customer", "conditional", ["multi_location_customer_organization"]],
  ["multi_location_hq", "multilocation.hq_procurement_owner", "全社契約・調達を管理する担当者", ["C6"], "ratifier", "payer_or_sponsor", "conditional", ["multi_location_customer_organization"]],
  ["multi_location_hq", "multilocation.hq_brand_reputation_owner", "ブランド一貫性・全拠点評判を管理する人", ["C5"], "champion", "prospective_customer", "conditional", ["multi_location_customer_organization"]],
  ["local_branch", "branch.local_manager", "支店・店舗単位の判断を行う責任者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["multi_location_customer_organization"]],
  ["local_branch", "branch.local_operator", "支店・店舗の現場運用を担う担当者", ["C4"], "operator", "end_user_or_beneficiary", "conditional", ["multi_location_customer_organization"]],
  ["local_branch", "branch.local_marketing_reputation_owner", "地域集客・口コミ・評判を管理する担当者", ["C5"], "champion", "prospective_customer", "conditional", ["multi_location_customer_organization"]],
  ["local_branch", "branch.local_customer_service_owner", "店舗利用者対応・サービス品質を管理する人", ["C4"], "operator", "prospective_customer", "conditional", ["multi_location_customer_organization"]],
  ["franchisee", "franchise.hq_decision_owner", "本部方針・全体導入を決める責任者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["franchise_recruitment"]],
  ["franchisee", "franchise.franchisee_owner", "加盟店として投資・導入を判断する経営者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["franchise_recruitment"]],
  ["franchisee", "franchise.location_operator", "加盟店舗の現場運用を担う人", ["C4"], "operator", "end_user_or_beneficiary", "conditional", ["franchise_recruitment"]],
  ["franchisee", "franchise.brand_compliance_reviewer", "ブランド基準・契約遵守を審査する担当者", ["C6"], "reviewer", "prospective_customer", "conditional", ["franchise_recruitment"]],
  ["public_nonprofit", "public.procurement_owner", "公共調達・入札・契約を管理する担当者", ["C6"], "ratifier", "payer_or_sponsor", "conditional", ["public_nonprofit_customer"]],
  ["public_nonprofit", "public.program_decision_owner", "事業・制度・支援プログラムを決める責任者", ["C3"], "decision_owner", "prospective_customer", "conditional", ["public_nonprofit_customer"]],
  ["public_nonprofit", "public.frontline_operator", "住民・利用者向けサービスを実施する担当者", ["C4"], "operator", "prospective_customer", "conditional", ["public_nonprofit_customer"]],
  ["public_nonprofit", "public.citizen_service_beneficiary", "公共サービスを実際に利用する住民・受益者", ["C1", "C4"], "recipient", "end_user_or_beneficiary", "selectable", ["public_nonprofit_customer"]],
  ["public_nonprofit", "public.compliance_accessibility_reviewer", "法令・アクセシビリティ・説明責任を審査する担当者", ["C6"], "reviewer", "prospective_customer", "conditional", ["public_nonprofit_customer"]],
  ["public_nonprofit", "nonprofit.institutional_funder", "助成・法人寄付・資金提供を判断する組織担当者", ["C3", "C5"], "funder", "payer_or_sponsor", "selectable", ["public_nonprofit_customer"]],
  ["public_nonprofit", "nonprofit.individual_donor_sponsor", "個人として寄付・継続支援を判断する人", ["C3", "C5"], "funder", "payer_or_sponsor", "selectable", ["public_nonprofit_customer"]],
  ["manufacturer_channel", "channel.manufacturer_product_owner", "メーカー側で製品・市場方針を担う責任者", ["C1", "C3"], "decision_owner", "prospective_customer", "conditional", []],
  ["manufacturer_channel", "channel.channel_strategy_owner", "卸・代理店・小売経路を設計する責任者", ["C5"], "champion", "prospective_customer", "conditional", []],
  ["manufacturer_channel", "channel.distributor_procurement_buyer", "卸・流通側で仕入れを判断する人", ["C2", "C3"], "payer", "partner_or_intermediary", "selectable", []],
  ["manufacturer_channel", "channel.dealer_retail_operator", "販売店・小売現場で販売と在庫を運用する人", ["C4"], "operator", "partner_or_intermediary", "selectable", []],
  ["manufacturer_channel", "channel.partner_sales_owner", "取引先開拓・販売支援を担うチャネル担当者", ["C5"], "champion", "prospective_customer", "conditional", []],
  ["subscription_membership", "subscription.acquisition_decider", "新規加入・契約開始を決める人", ["C3"], "decision_owner", "prospective_customer", "selectable", ["commerce_subscription", "adult_education", "media_brand"]],
  ["subscription_membership", "subscription.active_member_user", "会員サービスを継続利用する人", ["C4"], "end_user", "current_customer", "selectable", ["commerce_subscription", "adult_education", "media_brand"]],
  ["subscription_membership", "subscription.renewal_value_decider", "更新時に継続価値を判断する人", ["C8"], "existing_user", "current_customer", "selectable", ["commerce_subscription", "adult_education", "media_brand"]],
  ["subscription_membership", "subscription.churn_cancellation_decider", "休止・退会・解約を判断する人", ["C8"], "existing_user", "current_customer", "selectable", ["commerce_subscription", "adult_education", "media_brand"]],
  ["urgent_service", "urgent.need_owner", "緊急の課題を直接抱える本人・担当者", ["C1"], "need_owner", "prospective_customer", "selectable", ["urgent_service"]],
  ["urgent_service", "urgent.rapid_comparator", "限られた時間で複数候補を比較する人", ["C2"], "evaluator", "prospective_customer", "selectable", ["urgent_service"]],
  ["urgent_service", "urgent.booking_payment_decider", "連絡・依頼・費用負担を即時判断する人", ["C3"], "decision_owner", "payer_or_sponsor", "selectable", ["urgent_service"]],
  ["urgent_service", "urgent.family_proxy_decider", "本人に代わって緊急判断する家族・支援者", ["C7"], "proxy", "influencer_or_referrer", "selectable", ["urgent_service"]],
  ["urgent_service", "urgent.property_owner_manager_proxy", "所有者・管理会社として緊急対応を判断する人", ["C7"], "proxy", "payer_or_sponsor", "selectable", ["urgent_service"]]
];