-- Issue #123 / P4-C: action-specific contract, billing, entitlement, and checkpoint command boundary.
-- Function-only additive migration: no schema/table/column/RLS changes.

create or replace function recora_private.p4c_payload_fingerprint(p_payload jsonb)
returns text language sql immutable set search_path = '' as $$
  select pg_catalog.encode(extensions.digest(pg_catalog.convert_to(p_payload::text, 'utf8'), 'sha256'), 'hex');
$$;

create or replace function recora_private.p4c_contract_transition_allowed(p_previous_state recora_private.p4_contract_state,p_next_state recora_private.p4_contract_state)
returns boolean language sql immutable set search_path = '' as $$
  select ((p_previous_state is null and p_next_state='draft'::recora_private.p4_contract_state)
    or (p_previous_state='draft'::recora_private.p4_contract_state and p_next_state in('pending_activation'::recora_private.p4_contract_state,'canceled'::recora_private.p4_contract_state))
    or (p_previous_state='pending_activation'::recora_private.p4_contract_state and p_next_state in('active'::recora_private.p4_contract_state,'paused'::recora_private.p4_contract_state,'canceled'::recora_private.p4_contract_state,'ended'::recora_private.p4_contract_state))
    or (p_previous_state='active'::recora_private.p4_contract_state and p_next_state in('paused'::recora_private.p4_contract_state,'canceled'::recora_private.p4_contract_state,'ended'::recora_private.p4_contract_state))
    or (p_previous_state='paused'::recora_private.p4_contract_state and p_next_state in('active'::recora_private.p4_contract_state,'canceled'::recora_private.p4_contract_state,'ended'::recora_private.p4_contract_state)));
$$;

create or replace function recora_private.p4c_lifecycle_customer_reason(p_reason_code text)
returns text language sql immutable set search_path = '' as $$
  select case p_reason_code when 'active' then 'ok' when 'access_suspended' then 'lifecycle_access_suspended' when 'retained' then 'lifecycle_retained' when 'retained_restore_eligible' then 'lifecycle_retained' when 'deletion_scheduled' then 'lifecycle_deletion_scheduled' when 'deleting' then 'lifecycle_deleting' when 'deleted' then 'lifecycle_deleted' when 'deletion_failed' then 'lifecycle_deletion_failed' else 'lifecycle_unavailable' end;
$$;

create or replace function recora_private.p4c_customer_safe_contract_result(p_organization_id uuid,p_project_id uuid)
returns table(schema_version smallint,customer_access_allowed boolean,reason_code text,effective_from timestamptz,effective_until timestamptz,capabilities jsonb,limits jsonb)
language plpgsql stable security definer set search_path = '' as $$
declare entitlement_row record; lifecycle_row record; checkpoint_row record; lifecycle_reason text;
begin
  select * into entitlement_row from public.recora_resolve_current_entitlement_snapshot(p_organization_id,p_project_id);
  if entitlement_row.reason_code is distinct from 'ok' then return query select 1::smallint,false,entitlement_row.reason_code::text,null::timestamptz,null::timestamptz,'{}'::jsonb,'{}'::jsonb; return; end if;
  select * into lifecycle_row from public.recora_resolve_data_lifecycle_access(p_organization_id,p_project_id);
  lifecycle_reason:=recora_private.p4c_lifecycle_customer_reason(lifecycle_row.reason_code::text);
  if lifecycle_row.customer_access_allowed is not true then return query select 1::smallint,false,lifecycle_reason,entitlement_row.effective_from,entitlement_row.effective_until,coalesce(entitlement_row.capabilities,'{}'::jsonb),coalesce(entitlement_row.limits,'{}'::jsonb); return; end if;
  select * into checkpoint_row from public.recora_p4_resolve_checkpoint_gate(p_organization_id,p_project_id);
  if checkpoint_row.reason_code is distinct from 'ok' then return query select 1::smallint,false,checkpoint_row.reason_code::text,entitlement_row.effective_from,entitlement_row.effective_until,coalesce(entitlement_row.capabilities,'{}'::jsonb),coalesce(entitlement_row.limits,'{}'::jsonb); return; end if;
  return query select 1::smallint,true,'ok'::text,entitlement_row.effective_from,entitlement_row.effective_until,coalesce(entitlement_row.capabilities,'{}'::jsonb),coalesce(entitlement_row.limits,'{}'::jsonb);
end; $$;

create or replace function recora_private.p4c_record_command_receipt_direct(p_organization_id uuid,p_project_id uuid,p_command_type text,p_source_kind recora_private.p4_source_kind,p_source_namespace text,p_source_reference text,p_source_sequence bigint,p_payload_fingerprint text,p_request_id uuid,p_correlation_id uuid,p_idempotency_key text,p_outcome recora_private.p4_command_outcome,p_stable_reason recora_private.p4_reason,p_operator_audit_event_id uuid,p_operator_command_receipt_id uuid)
returns uuid language plpgsql security definer set search_path = '' as $$
declare created_id uuid; prior_id uuid;
begin
  select receipt_row.id into prior_id from recora_private.p4_command_receipts receipt_row where receipt_row.scope_key='organization:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'') and receipt_row.command_type=p_command_type and receipt_row.idempotency_key=p_idempotency_key;
  if prior_id is not null then return prior_id; end if;
  insert into recora_private.p4_command_receipts(organization_id,project_id,command_type,source_kind,source_namespace,source_reference,source_sequence,payload_fingerprint,request_id,correlation_id,idempotency_key,outcome,stable_reason,operator_audit_event_id,operator_command_receipt_id) values(p_organization_id,p_project_id,p_command_type,p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,p_payload_fingerprint,p_request_id,p_correlation_id,p_idempotency_key,p_outcome,p_stable_reason,p_operator_audit_event_id,p_operator_command_receipt_id) returning id into created_id;
  return created_id;
end; $$;

create or replace function recora_private.p4c_return_recorded_failure(p_organization_id uuid,p_project_id uuid,p_outcome recora_private.p4_command_outcome,p_stable_reason recora_private.p4_reason)
returns table(schema_version smallint,outcome text,stable_reason text,customer_access_allowed boolean,reason_code text,effective_from timestamptz,effective_until timestamptz,capabilities jsonb,limits jsonb)
language sql stable set search_path = '' as $$
  select 1::smallint,p_outcome::text,p_stable_reason::text,false,case when p_stable_reason='invalid_scope'::recora_private.p4_reason then 'invalid_scope' when p_stable_reason in('ordering_conflict'::recora_private.p4_reason,'reconciliation_required'::recora_private.p4_reason,'checkpoint_failed'::recora_private.p4_reason,'checkpoint_pending'::recora_private.p4_reason) then p_stable_reason::text else 'command_unavailable' end,null::timestamptz,null::timestamptz,'{}'::jsonb,'{}'::jsonb;
$$;
create or replace function public.recora_p4c_apply_contract_billing_entitlement_command(p_organization_id uuid,p_project_id uuid,p_source_kind recora_private.p4_source_kind,p_source_namespace text,p_source_reference text,p_source_sequence bigint,p_contract_reference text,p_next_contract_state recora_private.p4_contract_state,p_payment_fact_kind recora_private.p4_payment_fact_kind,p_payment_chain_key text,p_idempotency_key text,p_request_id uuid,p_correlation_id uuid,p_operator_audit_event_id uuid,p_operator_command_receipt_id uuid,p_corrects_payment_fact_id uuid default null)
returns table(schema_version smallint,outcome text,stable_reason text,customer_access_allowed boolean,reason_code text,effective_from timestamptz,effective_until timestamptz,capabilities jsonb,limits jsonb)
language plpgsql security definer set search_path = '' as $$
declare
  v_policy_row recora_private.plan_policy_versions%rowtype; v_contract_row recora_private.p4_contract_projections%rowtype; v_contract_found boolean:=false; v_prior_command recora_private.p4_command_receipts%rowtype; v_existing_source_command recora_private.p4_command_receipts%rowtype; v_prior_fact recora_private.p4_normalized_payment_facts%rowtype; v_lifecycle_row recora_private.data_lifecycle_current%rowtype;
  v_receipt_command record; v_contract_command record; v_payment_command record; v_checkpoint_command record; v_comp_checkpoint_command record; v_customer_row record; v_policy_summary jsonb; v_operator_summary jsonb; v_expected_operator_summary jsonb; v_policy_key text; v_policy_hash text; v_policy_schema_version smallint;
  v_comp_checkpoint_row recora_private.p4_downstream_checkpoints%rowtype; v_comp_outbox_row recora_private.p4_durable_outbox%rowtype; v_canonical_payload jsonb; v_canonical_fingerprint text; v_contract_id uuid; v_projection_policy_id uuid; v_snapshot_id uuid; v_billing_receipt_id uuid; v_checkpoint_id uuid; v_outbox_id uuid; v_comp_checkpoint_id uuid; v_comp_outbox_id uuid; v_event_sequence bigint;
  v_receipt_idempotency_key text:=p_idempotency_key||'.receipt'; v_policy_found boolean:=false; v_semantic_failure_reason recora_private.p4_reason:=null; v_derived_checkpoint_effect text:=null; v_next_receipt_state recora_private.p4_receipt_state:='applied'::recora_private.p4_receipt_state; v_return_outcome text:='applied'; v_return_stable_reason text:='ok';
begin
  if p_organization_id is null or p_source_kind is distinct from 'provider_fixture'::recora_private.p4_source_kind or not recora_private.p4_opaque(p_source_namespace) or not recora_private.p4_opaque(p_source_reference) or not recora_private.p4_opaque(p_contract_reference) or not recora_private.p4_opaque(p_payment_chain_key) or not recora_private.p4_opaque(p_idempotency_key) or char_length(p_idempotency_key)>96 or p_source_sequence is null or p_source_sequence<=0 or p_next_contract_state is null or p_payment_fact_kind is null or p_request_id is null or p_correlation_id is null or p_operator_audit_event_id is null or p_operator_command_receipt_id is null then
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  if not exists(select 1 from public.organizations organization_row where organization_row.id=p_organization_id) or (p_project_id is not null and not exists(select 1 from public.projects project_row where project_row.id=p_project_id and project_row.organization_id=p_organization_id)) then
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_scope'::recora_private.p4_reason); return; end if;

  select audit_event.after_summary into v_operator_summary
  from recora_operator.operator_command_receipts operator_receipt join recora_audit.operator_events audit_event on audit_event.id=operator_receipt.audit_event_id
  where operator_receipt.id=p_operator_command_receipt_id and operator_receipt.audit_event_id=p_operator_audit_event_id and operator_receipt.organization_id=p_organization_id and operator_receipt.project_id is not distinct from p_project_id and operator_receipt.request_id=p_request_id and operator_receipt.correlation_id=p_correlation_id and operator_receipt.action='p4c.contract.billing.apply' and audit_event.outcome='success'::recora_audit.operator_audit_outcome and audit_event.action='p4c.contract.billing.apply' and audit_event.organization_id=p_organization_id and audit_event.project_id is not distinct from p_project_id and ((p_project_id is null and operator_receipt.target_type='organization' and operator_receipt.target_id=p_organization_id) or (p_project_id is not null and operator_receipt.target_type='project' and operator_receipt.target_id=p_project_id));
  v_policy_summary:=v_operator_summary->'policy';
  if not found or jsonb_typeof(v_operator_summary) is distinct from 'object' or jsonb_typeof(v_policy_summary) is distinct from 'object' then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  v_policy_key:=v_policy_summary->>'key';
  if jsonb_typeof(v_policy_summary->'hash_chars')='array' and jsonb_array_length(v_policy_summary->'hash_chars')=64 then
    select string_agg(hash_char.char_value, '' order by hash_char.char_index) into v_policy_hash from jsonb_array_elements_text(v_policy_summary->'hash_chars') with ordinality as hash_char(char_value,char_index) where hash_char.char_value ~ '^[0-9a-f]$';
  else v_policy_hash:=v_policy_summary->>'hash'; end if;
  if (v_policy_summary->>'schema_version')~'^[1-9][0-9]{0,4}$' then v_policy_schema_version:=(v_policy_summary->>'schema_version')::smallint; end if;
  if not recora_private.p4_opaque(v_policy_key) or v_policy_hash !~ '^[0-9a-f]{64}$' or v_policy_schema_version is null then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  if not ((jsonb_typeof(v_policy_summary->'hash_chars')='array' and v_policy_summary=pg_catalog.jsonb_build_object('key',v_policy_key,'hash_chars',v_policy_summary->'hash_chars','schema_version',v_policy_schema_version)) or (v_policy_summary=pg_catalog.jsonb_build_object('key',v_policy_key,'hash',v_policy_hash,'schema_version',v_policy_schema_version))) then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  v_expected_operator_summary:=pg_catalog.jsonb_build_object('policy',v_policy_summary,'command',pg_catalog.jsonb_build_object('source_kind',p_source_kind::text,'source_namespace',p_source_namespace,'source_reference',p_source_reference,'source_sequence',p_source_sequence,'contract_reference',p_contract_reference,'next_contract_state',p_next_contract_state::text,'payment_fact_kind',p_payment_fact_kind::text,'payment_chain_key',p_payment_chain_key,'corrects_payment_fact_id_chars',case when p_corrects_payment_fact_id is null then null else pg_catalog.to_jsonb(pg_catalog.string_to_array(p_corrects_payment_fact_id::text,null)) end));
  if v_operator_summary is distinct from v_expected_operator_summary then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_policy_row from recora_private.plan_policy_versions version_row where version_row.policy_key=v_policy_key and version_row.policy_hash=v_policy_hash and version_row.policy_schema_version=v_policy_schema_version and version_row.effective_from<=now() and (version_row.effective_until is null or version_row.effective_until>now()) and not exists(select 1 from recora_private.plan_policy_versions successor where successor.supersedes_policy_version_id=version_row.id and successor.effective_from<=now() and (successor.effective_until is null or successor.effective_until>now()));
  v_policy_found:=found;
  v_canonical_payload:=pg_catalog.jsonb_build_object('schemaVersion',1,'organizationId',p_organization_id,'projectId',p_project_id,'sourceKind',p_source_kind::text,'sourceNamespace',p_source_namespace,'sourceReference',p_source_reference,'sourceSequence',p_source_sequence,'contractReference',p_contract_reference,'nextContractState',p_next_contract_state::text,'paymentFactKind',p_payment_fact_kind::text,'paymentChainKey',p_payment_chain_key,'correctsPaymentFactId',p_corrects_payment_fact_id,'authoritativePolicy',pg_catalog.jsonb_build_object('policyKey',v_policy_key,'policyVersionId',case when v_policy_found then v_policy_row.id else null end,'policySchemaVersion',v_policy_schema_version,'policyHash',v_policy_hash));
  v_canonical_fingerprint:=recora_private.p4c_payload_fingerprint(v_canonical_payload);
  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('organization:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'')||':billing.receipt:'||v_receipt_idempotency_key,0));
  if not v_policy_found then
    perform recora_private.p4c_record_command_receipt_direct(p_organization_id,p_project_id,'billing.receipt',p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,v_receipt_idempotency_key,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason,p_operator_audit_event_id,p_operator_command_receipt_id);
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('p4c:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'')||':'||p_source_namespace||':'||p_contract_reference,0));  select * into v_prior_command from recora_private.p4_command_receipts receipt_row where receipt_row.scope_key='organization:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'') and receipt_row.command_type='billing.receipt' and receipt_row.idempotency_key=v_receipt_idempotency_key for update;
  if found then
    if v_prior_command.source_kind=p_source_kind and v_prior_command.source_namespace=p_source_namespace and v_prior_command.source_reference=p_source_reference and v_prior_command.source_sequence=p_source_sequence and v_prior_command.payload_fingerprint=v_canonical_fingerprint then
      if v_prior_command.outcome='accepted'::recora_private.p4_command_outcome then set constraints all immediate; select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id); return query select v_customer_row.schema_version,'replayed'::text,'duplicate_command'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return; end if;
      return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_prior_command.outcome,v_prior_command.stable_reason); return;
    end if;
    insert into recora_private.p4_command_conflicts(prior_receipt_id,organization_id,project_id,command_type,source_namespace,source_reference,source_sequence,payload_fingerprint,request_id,correlation_id) values(v_prior_command.id,p_organization_id,p_project_id,'billing.receipt',p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id);
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'idempotency_conflict'::recora_private.p4_reason); return;
  end if;
  select * into v_existing_source_command from recora_private.p4_command_receipts receipt_row where receipt_row.scope_key='organization:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'') and receipt_row.command_type='billing.receipt' and receipt_row.source_kind=p_source_kind and receipt_row.source_namespace=p_source_namespace and receipt_row.source_reference=p_source_reference and receipt_row.source_sequence=p_source_sequence and receipt_row.idempotency_key<>v_receipt_idempotency_key for update;
  if found then
    perform recora_private.p4c_record_command_receipt_direct(p_organization_id,p_project_id,'billing.receipt',p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,v_receipt_idempotency_key,'rejected'::recora_private.p4_command_outcome,'idempotency_conflict'::recora_private.p4_reason,p_operator_audit_event_id,p_operator_command_receipt_id);
    insert into recora_private.p4_command_conflicts(prior_receipt_id,organization_id,project_id,command_type,source_namespace,source_reference,source_sequence,payload_fingerprint,request_id,correlation_id) values(v_existing_source_command.id,p_organization_id,p_project_id,'billing.receipt',p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id);
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'idempotency_conflict'::recora_private.p4_reason); return;
  end if;

  select * into v_contract_row from recora_private.p4_contract_projections projection_row where projection_row.organization_id=p_organization_id and projection_row.contract_reference=p_contract_reference for update; v_contract_found:=found;
  if v_contract_found and (v_contract_row.project_id is distinct from p_project_id or v_contract_row.source_namespace is distinct from p_source_namespace) then v_semantic_failure_reason:='invalid_scope'::recora_private.p4_reason;
  elsif v_contract_found and p_source_sequence<=v_contract_row.latest_source_sequence then v_semantic_failure_reason:='ordering_conflict'::recora_private.p4_reason;
  elsif (not v_contract_found and p_next_contract_state is distinct from 'draft'::recora_private.p4_contract_state) or (v_contract_found and not recora_private.p4c_contract_transition_allowed(v_contract_row.state,p_next_contract_state)) then v_semantic_failure_reason:='reconciliation_required'::recora_private.p4_reason;
  elsif p_payment_fact_kind in('payment_reversed'::recora_private.p4_payment_fact_kind,'payment_disputed'::recora_private.p4_payment_fact_kind) and p_corrects_payment_fact_id is null then v_semantic_failure_reason:='invalid_reference'::recora_private.p4_reason;
  elsif p_payment_fact_kind not in('payment_reversed'::recora_private.p4_payment_fact_kind,'payment_disputed'::recora_private.p4_payment_fact_kind) and p_corrects_payment_fact_id is not null then v_semantic_failure_reason:='invalid_reference'::recora_private.p4_reason;
  elsif p_corrects_payment_fact_id is not null then
    if not v_contract_found then v_semantic_failure_reason:='invalid_reference'::recora_private.p4_reason; else
      select * into v_prior_fact from recora_private.p4_normalized_payment_facts fact_row where fact_row.id=p_corrects_payment_fact_id for share;
      if not found or v_prior_fact.organization_id is distinct from p_organization_id or v_prior_fact.project_id is distinct from p_project_id or v_prior_fact.contract_id is distinct from v_contract_row.id or v_prior_fact.source_namespace is distinct from p_source_namespace or v_prior_fact.source_sequence>=p_source_sequence or v_prior_fact.payment_chain_key is distinct from p_payment_chain_key or v_prior_fact.corrects_fact_id is not null then v_semantic_failure_reason:='invalid_reference'::recora_private.p4_reason; end if;
    end if;
  end if;
  if v_semantic_failure_reason is not null then
    perform recora_private.p4c_record_command_receipt_direct(p_organization_id,p_project_id,'billing.receipt',p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,v_receipt_idempotency_key,'rejected'::recora_private.p4_command_outcome,v_semantic_failure_reason,p_operator_audit_event_id,p_operator_command_receipt_id);
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,v_semantic_failure_reason); return;
  end if;

  select * into v_receipt_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'billing.receipt',p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,v_receipt_idempotency_key,p_operator_audit_event_id,p_operator_command_receipt_id);
  if v_receipt_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_receipt_command.outcome,v_receipt_command.stable_reason); return; end if;
  select * into v_contract_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'contract.projection',p_source_kind,p_source_namespace,p_contract_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,p_idempotency_key||'.contract',p_operator_audit_event_id,p_operator_command_receipt_id);
  if v_contract_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_contract_command.outcome,v_contract_command.stable_reason); return; end if;

  if p_next_contract_state='active'::recora_private.p4_contract_state then
    begin insert into recora_private.entitlement_snapshots(organization_id,project_id,source_contract_reference,plan_policy_version_id,entitlement_schema_version,resolved_document,effective_from,effective_until,resolver_version,idempotency_key) values(p_organization_id,p_project_id,p_contract_reference,v_policy_row.id,v_policy_row.policy_schema_version,v_policy_row.policy_document,now(),v_policy_row.effective_until,'p4c.rpc.v2',p_idempotency_key||'.entitlement') returning id into v_snapshot_id;
    exception when unique_violation then select snapshot_row.id into v_snapshot_id from recora_private.entitlement_snapshots snapshot_row where snapshot_row.organization_id=p_organization_id and snapshot_row.project_id is not distinct from p_project_id and snapshot_row.idempotency_key=p_idempotency_key||'.entitlement'; end;
    if v_snapshot_id is null then raise exception 'P4-C entitlement snapshot could not be resolved'; end if; v_projection_policy_id:=v_policy_row.id;
    update recora_private.current_entitlement_snapshots pointer_row set snapshot_id=v_snapshot_id where pointer_row.organization_id=p_organization_id and pointer_row.project_id is not distinct from p_project_id;
    if not found then insert into recora_private.current_entitlement_snapshots(organization_id,project_id,snapshot_id) values(p_organization_id,p_project_id,v_snapshot_id); end if;
  else v_snapshot_id:=case when v_contract_found then v_contract_row.entitlement_snapshot_id else null::uuid end; v_projection_policy_id:=case when v_contract_found then v_contract_row.plan_policy_version_id else null::uuid end; end if;

  if not v_contract_found then
    insert into recora_private.p4_contract_projections(organization_id,project_id,contract_reference,source_namespace,state,latest_source_sequence,plan_policy_version_id,entitlement_snapshot_id,last_command_receipt_id) values(p_organization_id,p_project_id,p_contract_reference,p_source_namespace,'draft'::recora_private.p4_contract_state,p_source_sequence,null::uuid,null::uuid,v_contract_command.command_receipt_id) returning id into v_contract_id;
    insert into recora_private.p4_contract_events(contract_id,organization_id,event_sequence,source_namespace,source_reference,source_sequence,payload_fingerprint,previous_state,next_state,plan_policy_version_id,entitlement_snapshot_id,command_receipt_id,request_id,correlation_id) values(v_contract_id,p_organization_id,1,p_source_namespace,p_contract_reference,p_source_sequence,v_canonical_fingerprint,null::recora_private.p4_contract_state,'draft'::recora_private.p4_contract_state,null::uuid,null::uuid,v_contract_command.command_receipt_id,p_request_id,p_correlation_id);
  else
    v_contract_id:=v_contract_row.id; select coalesce(max(event_row.event_sequence),0)+1 into v_event_sequence from recora_private.p4_contract_events event_row where event_row.contract_id=v_contract_row.id;
    insert into recora_private.p4_contract_events(contract_id,organization_id,event_sequence,source_namespace,source_reference,source_sequence,payload_fingerprint,previous_state,next_state,plan_policy_version_id,entitlement_snapshot_id,command_receipt_id,request_id,correlation_id) values(v_contract_row.id,p_organization_id,v_event_sequence,p_source_namespace,p_contract_reference,p_source_sequence,v_canonical_fingerprint,v_contract_row.state,p_next_contract_state,v_projection_policy_id,v_snapshot_id,v_contract_command.command_receipt_id,p_request_id,p_correlation_id);
    update recora_private.p4_contract_projections projection_row set state=p_next_contract_state,latest_source_sequence=p_source_sequence,plan_policy_version_id=v_projection_policy_id,entitlement_snapshot_id=v_snapshot_id,last_command_receipt_id=v_contract_command.command_receipt_id where projection_row.id=v_contract_row.id;
  end if;  insert into recora_private.p4_billing_receipts(organization_id,project_id,contract_id,source_kind,source_namespace,source_reference,source_sequence,payload_fingerprint,processing_state,last_command_receipt_id,request_id,correlation_id) values(p_organization_id,p_project_id,v_contract_id,p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,'received'::recora_private.p4_receipt_state,v_receipt_command.command_receipt_id,p_request_id,p_correlation_id) returning id into v_billing_receipt_id;
  insert into recora_private.p4_billing_receipt_events(receipt_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_billing_receipt_id,p_organization_id,1,null::recora_private.p4_receipt_state,'received'::recora_private.p4_receipt_state,v_receipt_command.command_receipt_id,p_request_id,p_correlation_id);
  update recora_private.p4_billing_receipts receipt_row set processing_state='validated'::recora_private.p4_receipt_state where receipt_row.id=v_billing_receipt_id;
  insert into recora_private.p4_billing_receipt_events(receipt_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_billing_receipt_id,p_organization_id,2,'received'::recora_private.p4_receipt_state,'validated'::recora_private.p4_receipt_state,v_receipt_command.command_receipt_id,p_request_id,p_correlation_id);
  select * into v_payment_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'billing.payment_fact',p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,p_idempotency_key||'.payment',p_operator_audit_event_id,p_operator_command_receipt_id);
  if v_payment_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_payment_command.outcome,v_payment_command.stable_reason); return; end if;
  insert into recora_private.p4_normalized_payment_facts(receipt_id,organization_id,project_id,contract_id,source_namespace,source_reference,source_sequence,fact_kind,corrects_fact_id,command_receipt_id,request_id,correlation_id,payment_chain_key) values(v_billing_receipt_id,p_organization_id,p_project_id,v_contract_id,p_source_namespace,p_source_reference,p_source_sequence,p_payment_fact_kind,p_corrects_payment_fact_id,v_payment_command.command_receipt_id,p_request_id,p_correlation_id,p_payment_chain_key);
  update recora_private.p4_billing_receipts receipt_row set processing_state='applying'::recora_private.p4_receipt_state where receipt_row.id=v_billing_receipt_id;
  insert into recora_private.p4_billing_receipt_events(receipt_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_billing_receipt_id,p_organization_id,3,'validated'::recora_private.p4_receipt_state,'applying'::recora_private.p4_receipt_state,v_receipt_command.command_receipt_id,p_request_id,p_correlation_id);

  if p_next_contract_state in('paused'::recora_private.p4_contract_state,'canceled'::recora_private.p4_contract_state,'ended'::recora_private.p4_contract_state) or p_payment_fact_kind in('payment_failed'::recora_private.p4_payment_fact_kind,'payment_reversed'::recora_private.p4_payment_fact_kind,'payment_disputed'::recora_private.p4_payment_fact_kind) then v_derived_checkpoint_effect:='lifecycle.suspend'; end if;
  if v_derived_checkpoint_effect is null and p_next_contract_state='active'::recora_private.p4_contract_state and p_payment_fact_kind='payment_succeeded'::recora_private.p4_payment_fact_kind then
    select * into v_comp_checkpoint_row from recora_private.p4_downstream_checkpoints checkpoint_row where checkpoint_row.organization_id=p_organization_id and checkpoint_row.project_id is not distinct from p_project_id and checkpoint_row.blocks_customer_access and checkpoint_row.superseded_by_checkpoint_id is null and checkpoint_row.required_effect='lifecycle.suspend' and checkpoint_row.state in('pending'::recora_private.p4_checkpoint_state,'applying'::recora_private.p4_checkpoint_state,'failed'::recora_private.p4_checkpoint_state) order by checkpoint_row.created_at desc limit 1 for update;
    if found then
      select * into v_comp_outbox_row from recora_private.p4_durable_outbox outbox_row where outbox_row.checkpoint_id=v_comp_checkpoint_row.id and outbox_row.superseded_by_outbox_id is null order by outbox_row.created_at desc limit 1 for update;
      if found then
        select * into v_comp_checkpoint_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'lifecycle.checkpoint',p_source_kind,p_source_namespace,p_idempotency_key||'.compensate',p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,p_idempotency_key||'.checkpoint.compensate',p_operator_audit_event_id,p_operator_command_receipt_id);
        if v_comp_checkpoint_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_comp_checkpoint_command.outcome,v_comp_checkpoint_command.stable_reason); return; end if;
        insert into recora_private.p4_downstream_checkpoints(organization_id,project_id,command_receipt_id,required_effect,state,stable_reason,blocks_customer_access,correction_of_checkpoint_id) values(p_organization_id,p_project_id,v_comp_checkpoint_command.command_receipt_id,v_comp_checkpoint_row.required_effect,'pending'::recora_private.p4_checkpoint_state,'checkpoint_pending'::recora_private.p4_reason,true,v_comp_checkpoint_row.id) returning id into v_comp_checkpoint_id;
        insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_comp_checkpoint_id,p_organization_id,1,null::recora_private.p4_checkpoint_state,'pending'::recora_private.p4_checkpoint_state,v_comp_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
        update recora_private.p4_downstream_checkpoints set state='applying'::recora_private.p4_checkpoint_state where id=v_comp_checkpoint_id;
        insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_comp_checkpoint_id,p_organization_id,2,'pending'::recora_private.p4_checkpoint_state,'applying'::recora_private.p4_checkpoint_state,v_comp_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
        update recora_private.p4_downstream_checkpoints set state='completed'::recora_private.p4_checkpoint_state,stable_reason='ok'::recora_private.p4_reason where id=v_comp_checkpoint_id;
        insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_comp_checkpoint_id,p_organization_id,3,'applying'::recora_private.p4_checkpoint_state,'completed'::recora_private.p4_checkpoint_state,v_comp_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
        update recora_private.p4_downstream_checkpoints set superseded_by_checkpoint_id=v_comp_checkpoint_id where id=v_comp_checkpoint_row.id;
        insert into recora_private.p4_durable_outbox(checkpoint_id,command_receipt_id,organization_id,project_id,effect_kind,ordering_key,idempotency_key,state,stable_reason,correction_of_outbox_id) values(v_comp_checkpoint_id,v_comp_checkpoint_command.command_receipt_id,p_organization_id,p_project_id,v_comp_outbox_row.effect_kind,v_comp_outbox_row.ordering_key,p_idempotency_key||'.outbox.compensate','pending'::recora_private.p4_outbox_state,'checkpoint_pending'::recora_private.p4_reason,v_comp_outbox_row.id) returning id into v_comp_outbox_id;
        insert into recora_private.p4_outbox_events(outbox_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_comp_outbox_id,p_organization_id,1,null::recora_private.p4_outbox_state,'pending'::recora_private.p4_outbox_state,v_comp_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
        update recora_private.p4_durable_outbox set state='delivered'::recora_private.p4_outbox_state,stable_reason='ok'::recora_private.p4_reason,resolved_at=now() where id=v_comp_outbox_id;
        insert into recora_private.p4_outbox_events(outbox_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_comp_outbox_id,p_organization_id,2,'pending'::recora_private.p4_outbox_state,'delivered'::recora_private.p4_outbox_state,v_comp_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
        update recora_private.p4_durable_outbox set superseded_by_outbox_id=v_comp_outbox_id where id=v_comp_outbox_row.id;
      end if;
    end if;
  end if;
  if v_derived_checkpoint_effect is not null then
    select * into v_lifecycle_row from recora_private.data_lifecycle_current current_row where current_row.organization_id=p_organization_id and current_row.project_id is not distinct from p_project_id for share;
    if not found then raise exception 'P4-C checkpoint requires authoritative lifecycle state'; end if;
    select * into v_checkpoint_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'lifecycle.checkpoint',p_source_kind,p_source_namespace,p_source_reference,p_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,p_idempotency_key||'.checkpoint',p_operator_audit_event_id,p_operator_command_receipt_id);
    if v_checkpoint_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_checkpoint_command.outcome,v_checkpoint_command.stable_reason); return; end if;
    insert into recora_private.p4_downstream_checkpoints(organization_id,project_id,command_receipt_id,required_effect,state,stable_reason,blocks_customer_access) values(p_organization_id,p_project_id,v_checkpoint_command.command_receipt_id,v_derived_checkpoint_effect,'pending'::recora_private.p4_checkpoint_state,'checkpoint_pending'::recora_private.p4_reason,true) returning id into v_checkpoint_id;
    insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_checkpoint_id,p_organization_id,1,null::recora_private.p4_checkpoint_state,'pending'::recora_private.p4_checkpoint_state,v_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
    insert into recora_private.p4_durable_outbox(checkpoint_id,command_receipt_id,organization_id,project_id,effect_kind,ordering_key,idempotency_key,state,stable_reason) values(v_checkpoint_id,v_checkpoint_command.command_receipt_id,p_organization_id,p_project_id,v_derived_checkpoint_effect,p_source_sequence,p_idempotency_key||'.outbox','pending'::recora_private.p4_outbox_state,'checkpoint_pending'::recora_private.p4_reason) returning id into v_outbox_id;
    insert into recora_private.p4_outbox_events(outbox_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_outbox_id,p_organization_id,1,null::recora_private.p4_outbox_state,'pending'::recora_private.p4_outbox_state,v_checkpoint_command.command_receipt_id,p_request_id,p_correlation_id);
    v_return_outcome:='reconciliation_required'; v_return_stable_reason:='checkpoint_pending';
  end if;
  update recora_private.p4_billing_receipts receipt_row set processing_state=v_next_receipt_state where receipt_row.id=v_billing_receipt_id;
  insert into recora_private.p4_billing_receipt_events(receipt_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_billing_receipt_id,p_organization_id,4,'applying'::recora_private.p4_receipt_state,v_next_receipt_state,v_receipt_command.command_receipt_id,p_request_id,p_correlation_id);
  set constraints all immediate;
  select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id);
  return query select v_customer_row.schema_version,v_return_outcome,v_return_stable_reason,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return;
exception when foreign_key_violation or unique_violation or check_violation or not_null_violation or invalid_text_representation or raise_exception then
  return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return;
end; $$;
create or replace function public.recora_p4c_confirm_lifecycle_checkpoint_command(p_organization_id uuid,p_project_id uuid,p_checkpoint_id uuid,p_phase3_lifecycle_event_id uuid,p_idempotency_key text,p_request_id uuid,p_correlation_id uuid,p_operator_audit_event_id uuid,p_operator_command_receipt_id uuid)
returns table(schema_version smallint,outcome text,stable_reason text,customer_access_allowed boolean,reason_code text,effective_from timestamptz,effective_until timestamptz,capabilities jsonb,limits jsonb)
language plpgsql security definer set search_path = '' as $$
declare
  v_checkpoint_row recora_private.p4_downstream_checkpoints%rowtype; v_outbox_row recora_private.p4_durable_outbox%rowtype; v_lifecycle_event recora_private.data_lifecycle_events%rowtype; v_lifecycle_row recora_private.data_lifecycle_current%rowtype; v_prior_command recora_private.p4_command_receipts%rowtype;
  v_confirm_command record; v_customer_row record; v_operator_summary jsonb; v_expected_operator_summary jsonb; v_canonical_payload jsonb; v_canonical_fingerprint text; v_new_checkpoint_id uuid; v_new_outbox_id uuid; v_source_reference text:=p_idempotency_key||'.confirm'; v_receipt_idempotency_key text:=p_idempotency_key||'.checkpoint.confirm'; v_expected_reason text;
begin
  if p_organization_id is null or not exists(select 1 from public.organizations organization_row where organization_row.id=p_organization_id) or (p_project_id is not null and not exists(select 1 from public.projects project_row where project_row.id=p_project_id and project_row.organization_id=p_organization_id)) or p_checkpoint_id is null or p_phase3_lifecycle_event_id is null or not recora_private.p4_opaque(p_idempotency_key) or char_length(p_idempotency_key)>96 or p_request_id is null or p_correlation_id is null or p_operator_audit_event_id is null or p_operator_command_receipt_id is null then
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select audit_event.after_summary into v_operator_summary from recora_operator.operator_command_receipts operator_receipt join recora_audit.operator_events audit_event on audit_event.id=operator_receipt.audit_event_id where operator_receipt.id=p_operator_command_receipt_id and operator_receipt.audit_event_id=p_operator_audit_event_id and operator_receipt.organization_id=p_organization_id and operator_receipt.project_id is not distinct from p_project_id and operator_receipt.request_id=p_request_id and operator_receipt.correlation_id=p_correlation_id and operator_receipt.action='p4c.lifecycle.checkpoint.confirm' and audit_event.outcome='success'::recora_audit.operator_audit_outcome and audit_event.action='p4c.lifecycle.checkpoint.confirm' and audit_event.organization_id=p_organization_id and audit_event.project_id is not distinct from p_project_id and ((p_project_id is null and operator_receipt.target_type='organization' and operator_receipt.target_id=p_organization_id) or (p_project_id is not null and operator_receipt.target_type='project' and operator_receipt.target_id=p_project_id));
  if not found or jsonb_typeof(v_operator_summary) is distinct from 'object' then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('p4c:checkpoint:'||p_checkpoint_id::text,0));
  select * into v_checkpoint_row from recora_private.p4_downstream_checkpoints checkpoint_row where checkpoint_row.id=p_checkpoint_id and checkpoint_row.organization_id=p_organization_id and checkpoint_row.project_id is not distinct from p_project_id and checkpoint_row.blocks_customer_access for update;
  if not found then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_outbox_row from recora_private.p4_durable_outbox outbox_row where outbox_row.checkpoint_id=v_checkpoint_row.id order by outbox_row.created_at desc limit 1 for update;
  if not found then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_lifecycle_event from recora_private.data_lifecycle_events event_row where event_row.id=p_phase3_lifecycle_event_id and event_row.organization_id=p_organization_id and event_row.project_id is not distinct from p_project_id;
  select * into v_lifecycle_row from recora_private.data_lifecycle_current current_row where current_row.id=v_lifecycle_event.lifecycle_id and current_row.organization_id=p_organization_id and current_row.project_id is not distinct from p_project_id for share;
  v_expected_reason:='p4c.checkpoint.'||pg_catalog.translate(p_checkpoint_id::text,'0123456789-','abcdefghijz');
  if v_lifecycle_event.id is null or v_lifecycle_row.id is null or v_lifecycle_event.lifecycle_id is distinct from v_lifecycle_row.id or v_checkpoint_row.required_effect is distinct from 'lifecycle.suspend' or v_lifecycle_event.event_kind is distinct from 'state_transition' or v_lifecycle_event.next_state is distinct from 'access_suspended'::recora_private.data_lifecycle_state or v_lifecycle_event.occurred_at < v_checkpoint_row.created_at or v_lifecycle_event.reason is distinct from v_expected_reason or (v_checkpoint_row.phase3_lifecycle_id is not null and (v_checkpoint_row.phase3_lifecycle_id is distinct from v_lifecycle_event.lifecycle_id or v_lifecycle_event.version < v_checkpoint_row.expected_lifecycle_version)) then
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  v_expected_operator_summary:=pg_catalog.jsonb_build_object('checkpoint',pg_catalog.jsonb_build_object('checkpoint_id_chars',pg_catalog.to_jsonb(pg_catalog.string_to_array(p_checkpoint_id::text,null)),'phase3_lifecycle_event_id_chars',pg_catalog.to_jsonb(pg_catalog.string_to_array(p_phase3_lifecycle_event_id::text,null)),'required_effect',v_checkpoint_row.required_effect));
  if v_operator_summary is distinct from v_expected_operator_summary then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  v_canonical_payload:=pg_catalog.jsonb_build_object('schemaVersion',1,'organizationId',p_organization_id,'projectId',p_project_id,'checkpointId',p_checkpoint_id,'phase3LifecycleEventId',p_phase3_lifecycle_event_id,'phase3LifecycleId',v_lifecycle_event.lifecycle_id,'phase3LifecycleVersion',v_lifecycle_event.version,'phase3LifecycleState',v_lifecycle_event.next_state::text,'phase3Reason',v_lifecycle_event.reason,'requiredEffect',v_checkpoint_row.required_effect,'checkpointCreatedAt',v_checkpoint_row.created_at);
  v_canonical_fingerprint:=recora_private.p4c_payload_fingerprint(v_canonical_payload);
  select * into v_prior_command from recora_private.p4_command_receipts receipt_row where receipt_row.scope_key='organization:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'') and receipt_row.command_type='lifecycle.checkpoint' and receipt_row.idempotency_key=v_receipt_idempotency_key for update;
  if found then
    if v_prior_command.source_kind='manual'::recora_private.p4_source_kind and v_prior_command.source_namespace='p4c.lifecycle' and v_prior_command.source_reference=v_source_reference and v_prior_command.source_sequence=v_lifecycle_event.version and v_prior_command.payload_fingerprint=v_canonical_fingerprint then set constraints all immediate; select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id); return query select v_customer_row.schema_version,'replayed'::text,'duplicate_command'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return; end if;
    insert into recora_private.p4_command_conflicts(prior_receipt_id,organization_id,project_id,command_type,source_namespace,source_reference,source_sequence,payload_fingerprint,request_id,correlation_id) values(v_prior_command.id,p_organization_id,p_project_id,'lifecycle.checkpoint','p4c.lifecycle',v_source_reference,v_lifecycle_event.version,v_canonical_fingerprint,p_request_id,p_correlation_id);
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'idempotency_conflict'::recora_private.p4_reason); return;
  end if;
  if v_checkpoint_row.superseded_by_checkpoint_id is not null or v_checkpoint_row.state not in('pending'::recora_private.p4_checkpoint_state,'applying'::recora_private.p4_checkpoint_state,'failed'::recora_private.p4_checkpoint_state) or v_outbox_row.superseded_by_outbox_id is not null then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_confirm_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'lifecycle.checkpoint','manual'::recora_private.p4_source_kind,'p4c.lifecycle',v_source_reference,v_lifecycle_event.version,v_canonical_fingerprint,p_request_id,p_correlation_id,v_receipt_idempotency_key,p_operator_audit_event_id,p_operator_command_receipt_id);
  if v_confirm_command.outcome='replayed'::recora_private.p4_command_outcome then set constraints all immediate; select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id); return query select v_customer_row.schema_version,'replayed'::text,'duplicate_command'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return;
  elsif v_confirm_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_confirm_command.outcome,v_confirm_command.stable_reason); return; end if;
  insert into recora_private.p4_downstream_checkpoints(organization_id,project_id,command_receipt_id,required_effect,state,stable_reason,blocks_customer_access,correction_of_checkpoint_id) values(p_organization_id,p_project_id,v_confirm_command.command_receipt_id,v_checkpoint_row.required_effect,'pending'::recora_private.p4_checkpoint_state,'checkpoint_pending'::recora_private.p4_reason,true,v_checkpoint_row.id) returning id into v_new_checkpoint_id;
  insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_new_checkpoint_id,p_organization_id,1,null::recora_private.p4_checkpoint_state,'pending'::recora_private.p4_checkpoint_state,v_confirm_command.command_receipt_id,p_request_id,p_correlation_id);
  update recora_private.p4_downstream_checkpoints set state='applying'::recora_private.p4_checkpoint_state where id=v_new_checkpoint_id;
  insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_new_checkpoint_id,p_organization_id,2,'pending'::recora_private.p4_checkpoint_state,'applying'::recora_private.p4_checkpoint_state,v_confirm_command.command_receipt_id,p_request_id,p_correlation_id);
  update recora_private.p4_downstream_checkpoints set state='completed'::recora_private.p4_checkpoint_state,stable_reason='ok'::recora_private.p4_reason where id=v_new_checkpoint_id;
  insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_new_checkpoint_id,p_organization_id,3,'applying'::recora_private.p4_checkpoint_state,'completed'::recora_private.p4_checkpoint_state,v_confirm_command.command_receipt_id,p_request_id,p_correlation_id);
  update recora_private.p4_downstream_checkpoints set superseded_by_checkpoint_id=v_new_checkpoint_id where id=v_checkpoint_row.id;
  insert into recora_private.p4_durable_outbox(checkpoint_id,command_receipt_id,organization_id,project_id,effect_kind,ordering_key,idempotency_key,state,stable_reason,correction_of_outbox_id) values(v_new_checkpoint_id,v_confirm_command.command_receipt_id,p_organization_id,p_project_id,v_outbox_row.effect_kind,v_outbox_row.ordering_key,p_idempotency_key||'.outbox.confirm','pending'::recora_private.p4_outbox_state,'checkpoint_pending'::recora_private.p4_reason,v_outbox_row.id) returning id into v_new_outbox_id;
  insert into recora_private.p4_outbox_events(outbox_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_new_outbox_id,p_organization_id,1,null::recora_private.p4_outbox_state,'pending'::recora_private.p4_outbox_state,v_confirm_command.command_receipt_id,p_request_id,p_correlation_id);
  update recora_private.p4_durable_outbox set state='delivered'::recora_private.p4_outbox_state,stable_reason='ok'::recora_private.p4_reason,resolved_at=now() where id=v_new_outbox_id;
  insert into recora_private.p4_outbox_events(outbox_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_new_outbox_id,p_organization_id,2,'pending'::recora_private.p4_outbox_state,'delivered'::recora_private.p4_outbox_state,v_confirm_command.command_receipt_id,p_request_id,p_correlation_id);
  update recora_private.p4_durable_outbox set superseded_by_outbox_id=v_new_outbox_id where id=v_outbox_row.id;
  set constraints all immediate;
  select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id);
  return query select v_customer_row.schema_version,'applied'::text,'ok'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return;
exception when foreign_key_violation or unique_violation or check_violation or not_null_violation or invalid_text_representation or raise_exception then
  return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return;
end; $$;
create or replace function public.recora_p4c_reconcile_lifecycle_checkpoint_command(p_organization_id uuid,p_project_id uuid,p_checkpoint_id uuid,p_phase3_lifecycle_audit_event_id uuid,p_idempotency_key text,p_request_id uuid,p_correlation_id uuid,p_operator_audit_event_id uuid,p_operator_command_receipt_id uuid)
returns table(schema_version smallint,outcome text,stable_reason text,customer_access_allowed boolean,reason_code text,effective_from timestamptz,effective_until timestamptz,capabilities jsonb,limits jsonb)
language plpgsql security definer set search_path = '' as $$
declare
  v_checkpoint_row recora_private.p4_downstream_checkpoints%rowtype; v_outbox_row recora_private.p4_durable_outbox%rowtype; v_phase3_event recora_audit.operator_events%rowtype; v_prior_command recora_private.p4_command_receipts%rowtype; v_reconcile_command record; v_customer_row record; v_operator_summary jsonb; v_expected_operator_summary jsonb; v_canonical_payload jsonb; v_canonical_fingerprint text; v_checkpoint_event_sequence bigint; v_outbox_event_sequence bigint; v_source_reference text:=p_idempotency_key||'.reconcile'; v_receipt_idempotency_key text:=p_idempotency_key||'.checkpoint.reconcile'; v_original_checkpoint_receipt recora_private.p4_command_receipts%rowtype; v_original_outbox_receipt recora_private.p4_command_receipts%rowtype; v_expected_reason text; v_phase3_source_sequence bigint;
begin
  if p_organization_id is null or not exists(select 1 from public.organizations organization_row where organization_row.id=p_organization_id) or (p_project_id is not null and not exists(select 1 from public.projects project_row where project_row.id=p_project_id and project_row.organization_id=p_organization_id)) or p_checkpoint_id is null or p_phase3_lifecycle_audit_event_id is null or not recora_private.p4_opaque(p_idempotency_key) or char_length(p_idempotency_key)>96 or p_request_id is null or p_correlation_id is null or p_operator_audit_event_id is null or p_operator_command_receipt_id is null then
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select audit_event.after_summary into v_operator_summary from recora_operator.operator_command_receipts operator_receipt join recora_audit.operator_events audit_event on audit_event.id=operator_receipt.audit_event_id where operator_receipt.id=p_operator_command_receipt_id and operator_receipt.audit_event_id=p_operator_audit_event_id and operator_receipt.organization_id=p_organization_id and operator_receipt.project_id is not distinct from p_project_id and operator_receipt.request_id=p_request_id and operator_receipt.correlation_id=p_correlation_id and operator_receipt.action='p4c.lifecycle.checkpoint.reconcile' and audit_event.outcome='success'::recora_audit.operator_audit_outcome and audit_event.action='p4c.lifecycle.checkpoint.reconcile' and audit_event.organization_id=p_organization_id and audit_event.project_id is not distinct from p_project_id and ((p_project_id is null and operator_receipt.target_type='organization' and operator_receipt.target_id=p_organization_id) or (p_project_id is not null and operator_receipt.target_type='project' and operator_receipt.target_id=p_project_id));
  if not found or jsonb_typeof(v_operator_summary) is distinct from 'object' then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('p4c:checkpoint:'||p_checkpoint_id::text,0));
  select * into v_checkpoint_row from recora_private.p4_downstream_checkpoints checkpoint_row where checkpoint_row.id=p_checkpoint_id and checkpoint_row.organization_id=p_organization_id and checkpoint_row.project_id is not distinct from p_project_id and checkpoint_row.blocks_customer_access for update;
  if not found then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_outbox_row from recora_private.p4_durable_outbox outbox_row where outbox_row.checkpoint_id=v_checkpoint_row.id order by outbox_row.created_at desc limit 1 for update;
  if not found then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_phase3_event from recora_audit.operator_events audit_event where audit_event.id=p_phase3_lifecycle_audit_event_id and audit_event.organization_id=p_organization_id and audit_event.project_id is not distinct from p_project_id and audit_event.action='data_lifecycle.transition' and audit_event.outcome in('denied'::recora_audit.operator_audit_outcome,'failed'::recora_audit.operator_audit_outcome) and ((p_project_id is null and audit_event.target_type='organization' and audit_event.target_id=p_organization_id) or (p_project_id is not null and audit_event.target_type='project' and audit_event.target_id=p_project_id));
  v_expected_reason:='p4c.checkpoint.'||pg_catalog.translate(p_checkpoint_id::text,'0123456789-','abcdefghijz');
  if not found or v_checkpoint_row.required_effect is distinct from 'lifecycle.suspend' or v_phase3_event.occurred_at < v_checkpoint_row.created_at or v_phase3_event.reason is distinct from v_expected_reason or v_phase3_event.failure_reason_code not in('state_conflict','version_conflict','duplicate_request') or (v_phase3_event.before_summary->>'state') is distinct from 'active' or not ((v_phase3_event.before_summary->>'version')~'^[1-9][0-9]{0,18}$') or (v_checkpoint_row.expected_lifecycle_version is not null and (v_phase3_event.before_summary->>'version')::bigint < v_checkpoint_row.expected_lifecycle_version) then
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  v_phase3_source_sequence:=(v_phase3_event.before_summary->>'version')::bigint;
  v_expected_operator_summary:=pg_catalog.jsonb_build_object('checkpoint',pg_catalog.jsonb_build_object('checkpoint_id_chars',pg_catalog.to_jsonb(pg_catalog.string_to_array(p_checkpoint_id::text,null)),'phase3_lifecycle_audit_event_id_chars',pg_catalog.to_jsonb(pg_catalog.string_to_array(p_phase3_lifecycle_audit_event_id::text,null)),'required_effect',v_checkpoint_row.required_effect));
  if v_operator_summary is distinct from v_expected_operator_summary then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  v_canonical_payload:=pg_catalog.jsonb_build_object('schemaVersion',1,'organizationId',p_organization_id,'projectId',p_project_id,'checkpointId',p_checkpoint_id,'phase3LifecycleAuditEventId',p_phase3_lifecycle_audit_event_id,'phase3Outcome',v_phase3_event.outcome::text,'phase3FailureReason',v_phase3_event.failure_reason_code,'phase3BeforeState',v_phase3_event.before_summary->>'state','phase3BeforeVersion',v_phase3_source_sequence,'phase3Reason',v_phase3_event.reason,'requiredEffect',v_checkpoint_row.required_effect,'checkpointCreatedAt',v_checkpoint_row.created_at);
  v_canonical_fingerprint:=recora_private.p4c_payload_fingerprint(v_canonical_payload);
  select * into v_prior_command from recora_private.p4_command_receipts receipt_row where receipt_row.scope_key='organization:'||p_organization_id::text||coalesce(':project:'||p_project_id::text,'') and receipt_row.command_type='lifecycle.checkpoint' and receipt_row.idempotency_key=v_receipt_idempotency_key for update;
  if found then
    if v_prior_command.source_kind='manual'::recora_private.p4_source_kind and v_prior_command.source_namespace='p4c.lifecycle' and v_prior_command.source_reference=v_source_reference and v_prior_command.source_sequence=v_phase3_source_sequence and v_prior_command.payload_fingerprint=v_canonical_fingerprint then select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id); return query select v_customer_row.schema_version,'replayed'::text,'duplicate_command'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return; end if;
    insert into recora_private.p4_command_conflicts(prior_receipt_id,organization_id,project_id,command_type,source_namespace,source_reference,source_sequence,payload_fingerprint,request_id,correlation_id) values(v_prior_command.id,p_organization_id,p_project_id,'lifecycle.checkpoint','p4c.lifecycle',v_source_reference,v_phase3_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id);
    return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'idempotency_conflict'::recora_private.p4_reason); return;
  end if;
  if v_checkpoint_row.superseded_by_checkpoint_id is not null or v_checkpoint_row.state not in('pending'::recora_private.p4_checkpoint_state,'applying'::recora_private.p4_checkpoint_state,'failed'::recora_private.p4_checkpoint_state) or v_outbox_row.superseded_by_outbox_id is not null then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return; end if;
  select * into v_reconcile_command from public.recora_p4_record_command_receipt(p_organization_id,p_project_id,'lifecycle.checkpoint','manual'::recora_private.p4_source_kind,'p4c.lifecycle',v_source_reference,v_phase3_source_sequence,v_canonical_fingerprint,p_request_id,p_correlation_id,v_receipt_idempotency_key,p_operator_audit_event_id,p_operator_command_receipt_id);
  if v_reconcile_command.outcome='replayed'::recora_private.p4_command_outcome then select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id); return query select v_customer_row.schema_version,'replayed'::text,'duplicate_command'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return;
  elsif v_reconcile_command.outcome is distinct from 'accepted'::recora_private.p4_command_outcome then return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,v_reconcile_command.outcome,v_reconcile_command.stable_reason); return; end if;
  select * into v_original_checkpoint_receipt from recora_private.p4_command_receipts where id=v_checkpoint_row.command_receipt_id;
  select coalesce(max(event_row.event_sequence),0)+1 into v_checkpoint_event_sequence from recora_private.p4_checkpoint_events event_row where event_row.checkpoint_id=v_checkpoint_row.id;
  insert into recora_private.p4_checkpoint_events(checkpoint_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_checkpoint_row.id,p_organization_id,v_checkpoint_event_sequence,v_checkpoint_row.state,'reconciliation_required'::recora_private.p4_checkpoint_state,v_checkpoint_row.command_receipt_id,v_original_checkpoint_receipt.request_id,v_original_checkpoint_receipt.correlation_id);
  update recora_private.p4_downstream_checkpoints checkpoint_row set state='reconciliation_required'::recora_private.p4_checkpoint_state,stable_reason='reconciliation_required'::recora_private.p4_reason where checkpoint_row.id=v_checkpoint_row.id;
  if v_outbox_row.state <> 'reconciliation_required'::recora_private.p4_outbox_state then
    select * into v_original_outbox_receipt from recora_private.p4_command_receipts where id=v_outbox_row.command_receipt_id;
    select coalesce(max(event_row.event_sequence),0)+1 into v_outbox_event_sequence from recora_private.p4_outbox_events event_row where event_row.outbox_id=v_outbox_row.id;
    insert into recora_private.p4_outbox_events(outbox_id,organization_id,event_sequence,previous_state,next_state,command_receipt_id,request_id,correlation_id) values(v_outbox_row.id,p_organization_id,v_outbox_event_sequence,v_outbox_row.state,'reconciliation_required'::recora_private.p4_outbox_state,v_outbox_row.command_receipt_id,v_original_outbox_receipt.request_id,v_original_outbox_receipt.correlation_id);
    update recora_private.p4_durable_outbox outbox_row set state='reconciliation_required'::recora_private.p4_outbox_state,stable_reason='reconciliation_required'::recora_private.p4_reason,exhausted_at=now(),next_attempt_at=null where outbox_row.id=v_outbox_row.id;
  end if;
  set constraints all immediate;
  select * into v_customer_row from recora_private.p4c_customer_safe_contract_result(p_organization_id,p_project_id);
  return query select v_customer_row.schema_version,'reconciliation_required'::text,'reconciliation_required'::text,v_customer_row.customer_access_allowed,v_customer_row.reason_code,v_customer_row.effective_from,v_customer_row.effective_until,v_customer_row.capabilities,v_customer_row.limits; return;
exception when foreign_key_violation or unique_violation or check_violation or not_null_violation or invalid_text_representation or raise_exception then
  return query select * from recora_private.p4c_return_recorded_failure(p_organization_id,p_project_id,'rejected'::recora_private.p4_command_outcome,'invalid_reference'::recora_private.p4_reason); return;
end; $$;
comment on function public.recora_p4c_apply_contract_billing_entitlement_command(uuid,uuid,recora_private.p4_source_kind,text,text,bigint,text,recora_private.p4_contract_state,recora_private.p4_payment_fact_kind,text,text,uuid,uuid,uuid,uuid,uuid) is 'Issue #123 P4-C service-role-only apply boundary. It derives policy from immutable operator evidence, computes canonical fingerprints server-side, validates command semantics before accepted receipts, writes P4 receipt/payment/contract evidence atomically, and creates only pending checkpoint/outbox effects.';
comment on function public.recora_p4c_confirm_lifecycle_checkpoint_command(uuid,uuid,uuid,uuid,text,uuid,uuid,uuid,uuid) is 'Issue #123 P4-C service-role-only checkpoint completion boundary. It is idempotent, requires checkpoint-bound Phase 3 lifecycle event evidence, and records a completed P4 checkpoint/outbox correction with an independent command receipt.';
comment on function public.recora_p4c_reconcile_lifecycle_checkpoint_command(uuid,uuid,uuid,uuid,text,uuid,uuid,uuid,uuid) is 'Issue #123 P4-C service-role-only checkpoint reconciliation boundary. It is idempotent and requires checkpoint-bound failed or denied Phase 3 lifecycle operator evidence before moving a pending checkpoint/outbox to reconciliation_required.';

revoke all on function recora_private.p4c_payload_fingerprint(jsonb) from public, anon, authenticated;
revoke all on function recora_private.p4c_contract_transition_allowed(recora_private.p4_contract_state, recora_private.p4_contract_state) from public, anon, authenticated;
revoke all on function recora_private.p4c_lifecycle_customer_reason(text) from public, anon, authenticated;
revoke all on function recora_private.p4c_customer_safe_contract_result(uuid, uuid) from public, anon, authenticated;
revoke all on function recora_private.p4c_record_command_receipt_direct(uuid,uuid,text,recora_private.p4_source_kind,text,text,bigint,text,uuid,uuid,text,recora_private.p4_command_outcome,recora_private.p4_reason,uuid,uuid) from public, anon, authenticated;
revoke all on function recora_private.p4c_return_recorded_failure(uuid,uuid,recora_private.p4_command_outcome,recora_private.p4_reason) from public, anon, authenticated;

revoke all on function public.recora_p4c_apply_contract_billing_entitlement_command(uuid,uuid,recora_private.p4_source_kind,text,text,bigint,text,recora_private.p4_contract_state,recora_private.p4_payment_fact_kind,text,text,uuid,uuid,uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.recora_p4c_apply_contract_billing_entitlement_command(uuid,uuid,recora_private.p4_source_kind,text,text,bigint,text,recora_private.p4_contract_state,recora_private.p4_payment_fact_kind,text,text,uuid,uuid,uuid,uuid,uuid) to service_role;
revoke all on function public.recora_p4c_confirm_lifecycle_checkpoint_command(uuid,uuid,uuid,uuid,text,uuid,uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.recora_p4c_confirm_lifecycle_checkpoint_command(uuid,uuid,uuid,uuid,text,uuid,uuid,uuid,uuid) to service_role;
revoke all on function public.recora_p4c_reconcile_lifecycle_checkpoint_command(uuid,uuid,uuid,uuid,text,uuid,uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.recora_p4c_reconcile_lifecycle_checkpoint_command(uuid,uuid,uuid,uuid,text,uuid,uuid,uuid,uuid) to service_role;
